/** Curated trap-drill MC — 3 questions per top trap CKU (45 total). */

export const TRAP_DRILL_CKUS = [
  {
    ckuId: 'CKU-ACL',
    trapLabel: 'Forgetting the implicit deny.',
    objectiveId: '5.5',
  },
  {
    ckuId: 'CKU-SUBNETTING',
    trapLabel: 'Forgetting the "− 2" in the host formula.',
    objectiveId: '1.6',
  },
  {
    ckuId: 'CKU-ADMINISTRATIVE-DISTANCE',
    trapLabel: 'Assuming the lowest AD route always wins.',
    objectiveId: '3.2',
  },
  {
    ckuId: 'CKU-NATIVE-VLAN',
    trapLabel: 'Mismatched native VLANs.',
    objectiveId: '2.2',
  },
  {
    ckuId: 'CKU-OSPF',
    trapLabel: 'Using a subnet mask in the network statement.',
    objectiveId: '3.4',
  },
  {
    ckuId: 'CKU-DHCP-RELAY',
    trapLabel: 'Configure `ip helper-address` on the DHCP server interface.',
    objectiveId: '4.6',
  },
  {
    ckuId: 'CKU-STP-ROOT',
    trapLabel: 'Assuming the highest bridge priority becomes root.',
    objectiveId: '2.5',
  },
  {
    ckuId: 'CKU-NAT-PAT',
    trapLabel: 'Using static NAT when many hosts share one public IP.',
    objectiveId: '4.1',
  },
  {
    ckuId: 'CKU-DEFAULT-GATEWAY',
    trapLabel: 'Installing a default route without a reachable next-hop.',
    objectiveId: '3.3',
  },
  {
    ckuId: 'CKU-VLAN-TRUNK',
    trapLabel: 'Describing access-port behavior on a trunk question.',
    objectiveId: '2.2',
  },
  {
    ckuId: 'CKU-HSRP',
    trapLabel: 'Expecting both HSRP routers to forward simultaneously.',
    objectiveId: '3.5',
  },
  {
    ckuId: 'CKU-DHCP',
    trapLabel: 'Thinking the client sends the DHCP Offer.',
    objectiveId: '4.3',
  },
  {
    ckuId: 'CKU-STATIC-ROUTE',
    trapLabel: 'Using a wildcard mask in a static route command.',
    objectiveId: '3.3',
  },
  {
    ckuId: 'CKU-INTER-VLAN',
    trapLabel: 'Expecting VLANs to route without a Layer 3 device.',
    objectiveId: '2.1',
  },
  {
    ckuId: 'CKU-PORT-SECURITY',
    trapLabel: 'Enabling port security without specifying violation action.',
    objectiveId: '5.6',
  },
]

const QUESTIONS = [
  // CKU-ACL (3)
  {
    id: 'trap-acl-1',
    ckuId: 'CKU-ACL',
    trapLabel: 'Forgetting the implicit deny.',
    objectiveId: '5.5',
    question: 'An ACL ends with `permit tcp any any eq 443`. What happens to UDP/53 traffic?',
    choices: [
      'It is permitted because TCP was allowed',
      'It is denied by the implicit deny any at the end',
      'It is permitted until the ACL is applied to an interface',
      'It depends on the routing table',
    ],
    correctIndex: 1,
    explanation: 'Every ACL has an implicit deny any — traffic that does not match a permit is dropped.',
    type: 'scenario',
    concept: 'acl',
  },
  {
    id: 'trap-acl-2',
    ckuId: 'CKU-ACL',
    trapLabel: 'Misordering rules.',
    objectiveId: '5.5',
    question: 'Which ACL line order correctly blocks 10.1.1.0/24 but permits all other 10.0.0.0/8?',
    choices: [
      'deny 10.0.0.0 0.255.255.255 → permit 10.1.1.0 0.0.0.255',
      'deny 10.1.1.0 0.0.0.255 → permit 10.0.0.0 0.255.255.255',
      'permit 10.0.0.0 0.255.255.255 → deny 10.1.1.0 0.0.0.255',
      'permit any → deny 10.1.1.0 0.0.0.255',
    ],
    correctIndex: 1,
    explanation: 'First match wins — put the specific deny before the broad permit.',
    type: 'application',
    concept: 'acl',
  },
  {
    id: 'trap-acl-3',
    ckuId: 'CKU-ACL',
    trapLabel: 'Forgetting the implicit deny.',
    objectiveId: '5.5',
    question: 'You configure only `deny host 192.168.1.50`. What is the effect on other hosts?',
    choices: [
      'All other hosts are permitted explicitly',
      'All other hosts are denied by implicit deny any',
      'The ACL is invalid until a permit is added',
      'Only inbound traffic is affected',
    ],
    correctIndex: 1,
    explanation: 'A single deny still leaves the implicit deny any — you must add permit statements for allowed traffic.',
    type: 'scenario',
    concept: 'acl',
  },
  // CKU-SUBNETTING (3)
  {
    id: 'trap-sub-1',
    ckuId: 'CKU-SUBNETTING',
    trapLabel: 'Forgetting the "− 2" in the host formula.',
    objectiveId: '1.6',
    question: 'How many usable host addresses exist in a /26 subnet?',
    choices: ['64', '62', '32', '30'],
    correctIndex: 1,
    explanation: '6 host bits → 2^6 = 64 total, minus network and broadcast = 62 usable hosts.',
    type: 'application',
    concept: 'subnetting',
  },
  {
    id: 'trap-sub-2',
    ckuId: 'CKU-SUBNETTING',
    trapLabel: 'Confusing subnets (2^b) with hosts (2^h − 2).',
    objectiveId: '1.6',
    question: 'You borrow 3 bits for subnets in a /24. How many subnets and usable hosts per subnet?',
    choices: [
      '8 subnets, 32 hosts each',
      '8 subnets, 30 hosts each',
      '6 subnets, 32 hosts each',
      '6 subnets, 30 hosts each',
    ],
    correctIndex: 1,
    explanation: '3 borrowed bits → 2^3 = 8 subnets; 5 host bits remain → 2^5 − 2 = 30 usable hosts.',
    type: 'application',
    concept: 'subnetting',
  },
  {
    id: 'trap-sub-3',
    ckuId: 'CKU-SUBNETTING',
    trapLabel: 'Forgetting the "− 2" in the host formula.',
    objectiveId: '1.6',
    question: 'A /30 link is needed between two routers. How many usable addresses does it provide?',
    choices: ['4', '2', '1', '0'],
    correctIndex: 1,
    explanation: '/30 has 2 host bits → 4 total addresses minus network and broadcast = 2 usable (one per router).',
    type: 'definition',
    concept: 'subnetting',
  },
  // CKU-ADMINISTRATIVE-DISTANCE (3)
  {
    id: 'trap-ad-1',
    ckuId: 'CKU-ADMINISTRATIVE-DISTANCE',
    trapLabel: 'Assuming the lowest AD route always wins.',
    objectiveId: '3.2',
    question: 'A router has 10.0.0.0/8 via OSPF (AD 110) and 10.1.0.0/16 via static (AD 1). Which route is used for 10.1.5.10?',
    choices: [
      'The static /16 because AD 1 is lower',
      'The OSPF /8 because it was learned first',
      'The more specific /16 static route regardless of comparing to /8',
      'Both are installed and load-balanced',
    ],
    correctIndex: 2,
    explanation: 'Longest-prefix match decides first — /16 beats /8 even if the /8 has lower AD.',
    type: 'scenario',
    concept: 'routing',
  },
  {
    id: 'trap-ad-2',
    ckuId: 'CKU-ADMINISTRATIVE-DISTANCE',
    trapLabel: 'Forgetting AD 255 behavior.',
    objectiveId: '3.2',
    question: 'What happens to a route learned with administrative distance 255?',
    choices: [
      'It becomes the backup floating static',
      'It is installed with lowest priority',
      'It is considered unusable and not installed',
      'It is used only when no other route exists',
    ],
    correctIndex: 2,
    explanation: 'AD 255 marks a route as invalid — it never enters the routing table.',
    type: 'definition',
    concept: 'routing',
  },
  {
    id: 'trap-ad-3',
    ckuId: 'CKU-ADMINISTRATIVE-DISTANCE',
    trapLabel: 'Assuming the lowest AD route always wins.',
    objectiveId: '3.2',
    question: 'Two routes to 172.16.0.0/16 exist: EIGRP (AD 90) and OSPF (AD 110). Which is installed?',
    choices: [
      'OSPF because it has a lower metric',
      'EIGRP because AD 90 beats AD 110 for the same prefix',
      'Both are installed for ECMP',
      'Neither — AD must match to compare',
    ],
    correctIndex: 1,
    explanation: 'For the same prefix, lower AD wins — EIGRP (90) is preferred over OSPF (110).',
    type: 'scenario',
    concept: 'routing',
  },
  // CKU-NATIVE-VLAN (3)
  {
    id: 'trap-nvlan-1',
    ckuId: 'CKU-NATIVE-VLAN',
    trapLabel: 'Mismatched native VLANs.',
    objectiveId: '2.2',
    question: 'Switch A trunk native VLAN is 1; Switch B native VLAN is 99. What does CDP report?',
    choices: [
      'Nothing — trunks always work',
      'Native VLAN mismatch warning',
      'VTP domain error',
      'STP root inconsistency only',
    ],
    correctIndex: 1,
    explanation: 'Mismatched native VLANs trigger a CDP warning and can cause traffic leaks between VLANs.',
    type: 'troubleshooting',
    concept: 'vlan',
  },
  {
    id: 'trap-nvlan-2',
    ckuId: 'CKU-NATIVE-VLAN',
    trapLabel: 'Thinking all VLANs are tagged.',
    objectiveId: '2.2',
    question: 'On an 802.1Q trunk, which VLAN frames are sent untagged?',
    choices: [
      'All VLANs except VLAN 1',
      'Only the native VLAN',
      'Every VLAN above 100',
      'None — 802.1Q always tags',
    ],
    correctIndex: 1,
    explanation: 'The native VLAN is the only VLAN sent without an 802.1Q tag on a trunk.',
    type: 'definition',
    concept: 'vlan',
  },
  {
    id: 'trap-nvlan-3',
    ckuId: 'CKU-NATIVE-VLAN',
    trapLabel: 'Mismatched native VLANs.',
    objectiveId: '2.2',
    question: 'Best practice for native VLAN on a trunk to an untrusted switch?',
    choices: [
      'Leave it as VLAN 1',
      'Match VLAN 1 on both sides',
      'Change native VLAN to an unused VLAN and verify both ends match',
      'Disable the native VLAN with switchport trunk native vlan tag',
    ],
    correctIndex: 2,
    explanation: 'Move native VLAN off VLAN 1 and ensure both trunk ends use the same native VLAN ID.',
    type: 'application',
    concept: 'vlan',
  },
  // CKU-OSPF (3)
  {
    id: 'trap-ospf-1',
    ckuId: 'CKU-OSPF',
    trapLabel: 'Using a subnet mask in the network statement.',
    objectiveId: '3.4',
    question: 'Which OSPF network statement enables 192.168.10.0/24 on area 0?',
    choices: [
      'network 192.168.10.0 255.255.255.0 area 0',
      'network 192.168.10.0 0.0.0.255 area 0',
      'network 192.168.10.0/24 area 0',
      'network 192.168.10.0 0.255.255.255 area 0',
    ],
    correctIndex: 1,
    explanation: 'OSPF network statements use wildcard masks — /24 is 0.0.0.255, not a subnet mask.',
    type: 'application',
    concept: 'ospf',
  },
  {
    id: 'trap-ospf-2',
    ckuId: 'CKU-OSPF',
    trapLabel: 'Expecting DR/BDR on point-to-point links.',
    objectiveId: '3.4',
    question: 'On a serial point-to-point OSPF link, how many DR/BDR are elected?',
    choices: ['Two — one DR and one BDR', 'One DR only', 'None — DR/BDR are not elected', 'Depends on priority only'],
    correctIndex: 2,
    explanation: 'Point-to-point links skip DR/BDR election — only multi-access segments elect them.',
    type: 'definition',
    concept: 'ospf',
  },
  {
    id: 'trap-ospf-3',
    ckuId: 'CKU-OSPF',
    trapLabel: 'Using a subnet mask in the network statement.',
    objectiveId: '3.4',
    question: 'To match all interfaces in 10.0.0.0/8 for OSPF area 1, which wildcard is correct?',
    choices: ['255.0.0.0', '0.255.255.255', '255.255.255.0', '0.0.0.255'],
    correctIndex: 1,
    explanation: 'Wildcard 0.255.255.255 matches any address in 10.0.0.0/8 for the OSPF network command.',
    type: 'application',
    concept: 'ospf',
  },
  // CKU-DHCP-RELAY (3)
  {
    id: 'trap-dhcp-relay-1',
    ckuId: 'CKU-DHCP-RELAY',
    trapLabel: 'Configure `ip helper-address` on the DHCP server interface.',
    objectiveId: '4.6',
    question: 'Clients on VLAN 10 (192.168.10.0/24) need DHCP from a server at 10.0.0.5. Where do you configure `ip helper-address 10.0.0.5`?',
    choices: [
      'On the DHCP server\'s interface facing the clients',
      'On R1\'s VLAN 10 SVI or subinterface facing the client subnet',
      'Globally on the DHCP server router',
      'On every client switch access port',
    ],
    correctIndex: 1,
    explanation: 'The relay (helper-address) goes on the router interface facing the client subnet — not on the remote DHCP server.',
    type: 'application',
    concept: 'dhcp-relay',
  },
  {
    id: 'trap-dhcp-relay-2',
    ckuId: 'CKU-DHCP-RELAY',
    trapLabel: 'DHCP relay works without IP connectivity to the server.',
    objectiveId: '4.6',
    question: 'You added `ip helper-address` on R1 but clients still get no lease. R1 cannot ping 10.0.0.5. What is the most likely issue?',
    choices: [
      'Helper-address must use UDP port 67 on the client VLAN',
      'The relay router lacks a routable path to the DHCP server',
      'Clients must run `ip helper-address` locally',
      'DHCP relay only works on directly connected server subnets',
    ],
    correctIndex: 1,
    explanation: 'The relay router must reach the remote server — helper-address forwards broadcasts, but return traffic needs routing.',
    type: 'troubleshooting',
    concept: 'dhcp-relay',
  },
  {
    id: 'trap-dhcp-relay-3',
    ckuId: 'CKU-DHCP-RELAY',
    trapLabel: 'Configure `ip helper-address` on the DHCP server interface.',
    objectiveId: '4.6',
    question: 'Which statement about `ip helper-address` is correct?',
    choices: [
      'It turns the router into a DHCP server',
      'It converts local broadcasts into unicast toward a remote DHCP server',
      'It must be configured on both the client and server routers',
      'It replaces the need for a default gateway on clients',
    ],
    correctIndex: 1,
    explanation: 'Helper-address listens for DHCP (and other) broadcasts on a client-facing interface and forwards them to the configured server IP.',
    type: 'definition',
    concept: 'dhcp-relay',
  },
  // CKU-STP-ROOT (3)
  {
    id: 'trap-stp-root-1',
    ckuId: 'CKU-STP-ROOT',
    trapLabel: 'Assuming the highest bridge priority becomes root.',
    objectiveId: '2.5',
    question: 'Switch A priority 32768, Switch B priority 4096. Which becomes the STP root bridge?',
    choices: [
      'Switch A — higher numeric priority wins',
      'Switch B — lowest bridge priority wins',
      'Both share root via load balancing',
      'The switch with the lowest MAC always wins regardless of priority',
    ],
    correctIndex: 1,
    explanation: 'Lowest bridge priority wins root election — 4096 beats 32768.',
    type: 'scenario',
    concept: 'stp',
  },
  {
    id: 'trap-stp-root-2',
    ckuId: 'CKU-STP-ROOT',
    trapLabel: 'Assuming the highest bridge priority becomes root.',
    objectiveId: '2.5',
    question: 'You want SW2 to remain the permanent root. Which command on SW2 is best?',
    choices: [
      'spanning-tree vlan 1 priority 61440',
      'spanning-tree vlan 1 root primary',
      'spanning-tree vlan 1 priority 32768',
      'spanning-tree portfast default on all ports',
    ],
    correctIndex: 1,
    explanation: '`spanning-tree vlan X root primary` lowers priority to a well-known root value; portfast does not affect root election.',
    type: 'application',
    concept: 'stp',
  },
  {
    id: 'trap-stp-root-3',
    ckuId: 'CKU-STP-ROOT',
    trapLabel: 'Expecting STP to drop all user traffic on blocking ports.',
    objectiveId: '2.5',
    question: 'What is the purpose of the STP blocking state on a redundant link?',
    choices: [
      'Drop all user traffic permanently on that link',
      'Prevent Layer 2 loops while keeping a backup path ready',
      'Block only broadcast traffic but forward unicast',
      'Indicate the link failed physically',
    ],
    correctIndex: 1,
    explanation: 'Blocking prevents loops by not forwarding data frames — the port stays in standby so STP can unblock if the active path fails.',
    type: 'definition',
    concept: 'stp',
  },
  // CKU-NAT-PAT (3)
  {
    id: 'trap-nat-pat-1',
    ckuId: 'CKU-NAT-PAT',
    trapLabel: 'Using static NAT when many hosts share one public IP.',
    objectiveId: '4.1',
    question: 'A home router has one public IP and 20 inside hosts browsing the web. Which NAT type is required?',
    choices: [
      'Static NAT — one inside to one outside mapping',
      'Dynamic NAT pool with 20 public addresses',
      'PAT (NAT overload) using unique source ports',
      'No NAT — private addresses route globally',
    ],
    correctIndex: 2,
    explanation: 'Many inside hosts sharing one public IP requires PAT/overload — unique TCP/UDP source ports distinguish sessions.',
    type: 'scenario',
    concept: 'nat',
  },
  {
    id: 'trap-nat-pat-2',
    ckuId: 'CKU-NAT-PAT',
    trapLabel: 'Forgetting inside/outside interface labels.',
    objectiveId: '4.1',
    question: 'NAT is configured but translations never appear in `show ip nat translations`. What is a common CCNA trap?',
    choices: [
      'ACL is missing on the inside interface',
      'Inside and outside interfaces were not labeled before configuring NAT',
      'PAT requires IPv6 on the outside interface',
      'Static routes override NAT entries',
    ],
    correctIndex: 1,
    explanation: 'Label interfaces `ip nat inside` and `ip nat outside` first — NAT fails silently without correct direction.',
    type: 'troubleshooting',
    concept: 'nat',
  },
  {
    id: 'trap-nat-pat-3',
    ckuId: 'CKU-NAT-PAT',
    trapLabel: 'Using static NAT when many hosts share one public IP.',
    objectiveId: '4.1',
    question: 'Which IOS command enables PAT for the 192.168.1.0/24 ACL using the outside interface address?',
    choices: [
      'ip nat inside source static 192.168.1.0 255.255.255.0 interface GigabitEthernet0/0',
      'ip nat inside source list 1 interface GigabitEthernet0/0 overload',
      'ip nat outside source list 1 interface GigabitEthernet0/0 overload',
      'ip nat pool mypool 192.168.1.0 192.168.1.255 netmask 255.255.255.0',
    ],
    correctIndex: 1,
    explanation: 'PAT uses `ip nat inside source list <acl> interface <outside> overload` — inside source, not outside source.',
    type: 'application',
    concept: 'nat',
  },
  // CKU-DEFAULT-GATEWAY (3)
  {
    id: 'trap-dgw-1',
    ckuId: 'CKU-DEFAULT-GATEWAY',
    trapLabel: 'Installing a default route without a reachable next-hop.',
    objectiveId: '3.3',
    question: 'R1 has `ip route 0.0.0.0 0.0.0.0 203.0.113.1` but the next-hop is unreachable. What appears in the routing table?',
    choices: [
      'The default route installs and traffic is black-holed',
      'The static default is not installed until the next-hop is reachable',
      'OSPF automatically replaces the static default',
      'The route installs with AD 255',
    ],
    correctIndex: 1,
    explanation: 'A static route is added only if the next-hop is reachable (or the exit interface is up for connected-style statics).',
    type: 'scenario',
    concept: 'routing',
  },
  {
    id: 'trap-dgw-2',
    ckuId: 'CKU-DEFAULT-GATEWAY',
    trapLabel: 'Confusing default route with default gateway on hosts.',
    objectiveId: '3.3',
    question: 'A PC cannot reach the Internet but can ping its default gateway. Which device most likely lacks a default route?',
    choices: [
      'The PC — reinstall the NIC driver',
      'The access switch — add `ip default-gateway`',
      'The edge router toward the ISP',
      'The DNS server only',
    ],
    correctIndex: 2,
    explanation: 'Hosts point to a default gateway; the router needs its own default route (or full routing) toward the upstream ISP.',
    type: 'troubleshooting',
    concept: 'routing',
  },
  {
    id: 'trap-dgw-3',
    ckuId: 'CKU-DEFAULT-GATEWAY',
    trapLabel: 'Installing a default route without a reachable next-hop.',
    objectiveId: '3.3',
    question: 'Which command advertises a default route into OSPF area 0 from R1?',
    choices: [
      'ip route 0.0.0.0 0.0.0.0 Null0',
      'default-information originate',
      'router ospf 1 → default-information originate',
      'network 0.0.0.0 255.255.255.255 area 0',
    ],
    correctIndex: 2,
    explanation: 'Inside OSPF router config, `default-information originate` injects a default if R1 already has one configured.',
    type: 'application',
    concept: 'ospf',
  },
  // CKU-VLAN-TRUNK (3)
  {
    id: 'trap-trunk-1',
    ckuId: 'CKU-VLAN-TRUNK',
    trapLabel: 'Describing access-port behavior on a trunk question.',
    objectiveId: '2.2',
    question: 'Which link type carries multiple VLANs with 802.1Q tags?',
    choices: [
      'Access port to an end host',
      'Trunk between two switches',
      'Console cable between routers',
      'Loopback interface on a router',
    ],
    correctIndex: 1,
    explanation: 'Trunks tag frames with VLAN IDs — access ports carry a single VLAN untagged to end devices.',
    type: 'definition',
    concept: 'vlan',
  },
  {
    id: 'trap-trunk-2',
    ckuId: 'CKU-VLAN-TRUNK',
    trapLabel: 'Expecting a trunk to route between VLANs.',
    objectiveId: '2.2',
    question: 'VLAN 10 and VLAN 20 exist on SW1. Can a trunk alone let VLAN 10 hosts reach VLAN 20 hosts?',
    choices: [
      'Yes — trunks automatically route between VLANs',
      'No — trunks extend L2 VLANs; inter-VLAN traffic needs a router or L3 switch',
      'Yes — if both VLANs share the same native VLAN',
      'Only if DTP negotiates routing',
    ],
    correctIndex: 1,
    explanation: 'Trunks carry tagged VLAN frames at Layer 2 — routing between VLANs requires an SVI or router-on-a-stick.',
    type: 'scenario',
    concept: 'vlan',
  },
  {
    id: 'trap-trunk-3',
    ckuId: 'CKU-VLAN-TRUNK',
    trapLabel: 'Describing access-port behavior on a trunk question.',
    objectiveId: '2.2',
    question: 'Which command converts SW1 Gi0/1 to an 802.1Q trunk?',
    choices: [
      'switchport mode access',
      'switchport mode trunk',
      'switchport trunk native vlan routing',
      'vlan trunk encapsulation dot1q only (no mode change)',
    ],
    correctIndex: 1,
    explanation: '`switchport mode trunk` (after `switchport trunk encapsulation dot1q` on older platforms) enables tagged multi-VLAN forwarding.',
    type: 'application',
    concept: 'vlan',
  },
  // CKU-HSRP (3)
  {
    id: 'trap-hsrp-1',
    ckuId: 'CKU-HSRP',
    trapLabel: 'Expecting both HSRP routers to forward simultaneously.',
    objectiveId: '3.5',
    question: 'R1 and R2 run HSRP group 1 with virtual IP 192.168.1.1. R1 is Active, R2 is Standby. Who handles client traffic to 192.168.1.1?',
    choices: [
      'Both routers load-balance equally',
      'Only the Active router (R1) forwards until it fails',
      'Only the Standby router forwards by default',
      'Clients pick whichever router responds first to ARP',
    ],
    correctIndex: 1,
    explanation: 'HSRP Active router owns the virtual MAC/IP — Standby takes over only if Active fails (unless preempt changes timing).',
    type: 'scenario',
    concept: 'hsrp',
  },
  {
    id: 'trap-hsrp-2',
    ckuId: 'CKU-HSRP',
    trapLabel: 'Confusing HSRP with VRRP standard.',
    objectiveId: '3.5',
    question: 'Which FHRP is Cisco-proprietary (not the IEEE open standard)?',
    choices: [
      'VRRP',
      'HSRP',
      'Both are IEEE standards',
      'Proxy ARP',
    ],
    correctIndex: 1,
    explanation: 'HSRP is Cisco-proprietary; VRRP (RFC 5798) is the open multi-vendor standard.',
    type: 'definition',
    concept: 'hsrp',
  },
  {
    id: 'trap-hsrp-3',
    ckuId: 'CKU-HSRP',
    trapLabel: 'Expecting both HSRP routers to forward simultaneously.',
    objectiveId: '3.5',
    question: 'R1 should be preferred HSRP Active when it returns online. Which settings on R1 are required?',
    choices: [
      'standby 1 priority 100 (default only)',
      'standby 1 priority 150 and standby 1 preempt',
      'standby 1 track interface Gi0/1 only — no priority change',
      'vrrp 1 priority 150',
    ],
    correctIndex: 1,
    explanation: 'Higher priority plus preempt lets R1 reclaim Active when it comes back — default priority 100 does not guarantee preference.',
    type: 'application',
    concept: 'hsrp',
  },
  // CKU-DHCP (3)
  {
    id: 'trap-dhcp-1',
    ckuId: 'CKU-DHCP',
    trapLabel: 'Thinking the client sends the DHCP Offer.',
    objectiveId: '4.3',
    question: 'In DORA, who sends the DHCP Offer message?',
    choices: [
      'The client',
      'The DHCP server',
      'The default gateway router',
      'The DNS server',
    ],
    correctIndex: 1,
    explanation: 'DORA: Discover (client) → Offer (server) → Request (client) → Acknowledge (server).',
    type: 'definition',
    concept: 'dhcp',
  },
  {
    id: 'trap-dhcp-2',
    ckuId: 'CKU-DHCP',
    trapLabel: 'Thinking DNS and DHCP are unrelated.',
    objectiveId: '4.3',
    question: 'How does a DHCP client typically learn which DNS server to use?',
    choices: [
      'It hardcodes 8.8.8.8 automatically',
      'DHCP option 6 in the Ack message',
      'The switch adds DNS via CDP',
      'ARP resolves the DNS server MAC',
    ],
    correctIndex: 1,
    explanation: 'DHCP option 6 delivers DNS server addresses — DHCP and DNS work together for name resolution.',
    type: 'application',
    concept: 'dhcp',
  },
  {
    id: 'trap-dhcp-3',
    ckuId: 'CKU-DHCP',
    trapLabel: 'Thinking the client sends the DHCP Offer.',
    objectiveId: '4.3',
    question: 'A client sends DHCP Discover as a broadcast. What must happen before it receives an Offer?',
    choices: [
      'The client must unicast to port 443 first',
      'A DHCP server (or relay) must hear the Discover and respond',
      'The switch must tag the frame with VLAN 99',
      'The client configures a static IP temporarily',
    ],
    correctIndex: 1,
    explanation: 'Discover is a broadcast — a server on the subnet or a relay toward a remote server must answer with Offer.',
    type: 'scenario',
    concept: 'dhcp',
  },
  // CKU-STATIC-ROUTE (3)
  {
    id: 'trap-static-1',
    ckuId: 'CKU-STATIC-ROUTE',
    trapLabel: 'Using a wildcard mask in a static route command.',
    objectiveId: '3.3',
    question: 'Which static route syntax is valid on Cisco IOS?',
    choices: [
      'ip route 172.16.0.0 0.0.255.255 10.0.0.1',
      'ip route 172.16.0.0 255.255.0.0 10.0.0.1',
      'ip static-route 172.16.0.0/16 10.0.0.1',
      'ip route 172.16.0.0 255.255.0.0 area 0',
    ],
    correctIndex: 1,
    explanation: 'Static routes use subnet masks (255.255.0.0 for /16) — wildcard masks belong in ACLs and OSPF network statements.',
    type: 'application',
    concept: 'routing',
  },
  {
    id: 'trap-static-2',
    ckuId: 'CKU-STATIC-ROUTE',
    trapLabel: 'A static route in config always appears in the routing table.',
    objectiveId: '3.3',
    question: 'You configured `ip route 10.0.0.0 255.0.0.0 192.168.1.1` but Gi0/0 (192.168.1.0/30) is shutdown. Is the route in the table?',
    choices: [
      'Yes — static routes always install',
      'No — the next-hop interface/path is down',
      'Yes — with AD 255',
      'Only if OSPF redistributes it',
    ],
    correctIndex: 1,
    explanation: 'Static routes need a reachable next-hop or up exit interface — a down path prevents installation.',
    type: 'troubleshooting',
    concept: 'routing',
  },
  {
    id: 'trap-static-3',
    ckuId: 'CKU-STATIC-ROUTE',
    trapLabel: 'Using a wildcard mask in a static route command.',
    objectiveId: '3.3',
    question: 'To reach 10.10.0.0/16 via directly connected serial link (no next-hop IP), which is correct?',
    choices: [
      'ip route 10.10.0.0 255.255.0.0 Serial0/0/0',
      'ip route 10.10.0.0 0.0.255.255 Serial0/0/0',
      'ip route 10.10.0.0/16 Serial0/0/0',
      'static route 10.10.0.0 Serial0/0/0',
    ],
    correctIndex: 0,
    explanation: 'Point-to-point statics can use an exit interface — still with a proper subnet mask, not a wildcard.',
    type: 'application',
    concept: 'routing',
  },
  // CKU-INTER-VLAN (3)
  {
    id: 'trap-intervlan-1',
    ckuId: 'CKU-INTER-VLAN',
    trapLabel: 'Expecting VLANs to route without a Layer 3 device.',
    objectiveId: '2.1',
    question: 'Hosts in VLAN 10 cannot ping hosts in VLAN 20 on the same campus switch. Both VLANs exist on SW1. What is missing?',
    choices: [
      'Another access switch in VLAN 10',
      'A router or L3 switch SVI to route between VLANs',
      'A longer UTP cable between floors',
      'Disabling STP on SW1',
    ],
    correctIndex: 1,
    explanation: 'VLANs are separate broadcast domains — inter-VLAN traffic requires Layer 3 routing (SVI or router-on-a-stick).',
    type: 'scenario',
    concept: 'vlan',
  },
  {
    id: 'trap-intervlan-2',
    ckuId: 'CKU-INTER-VLAN',
    trapLabel: 'Adding L2 switch capacity instead of L3 routing.',
    objectiveId: '2.1',
    question: 'Can installing a second Layer 2 switch fix inter-VLAN connectivity?',
    choices: [
      'Yes — more switches bridge VLANs automatically',
      'No — another L2 switch extends VLANs but does not route between them',
      'Yes — if both switches use the same management VLAN',
      'Only if you enable DTP routing',
    ],
    correctIndex: 1,
    explanation: 'Extra L2 switches add ports in the same VLANs — they do not provide inter-VLAN routing.',
    type: 'definition',
    concept: 'vlan',
  },
  {
    id: 'trap-intervlan-3',
    ckuId: 'CKU-INTER-VLAN',
    trapLabel: 'Trunking between end hosts instead of L3 routing.',
    objectiveId: '2.1',
    question: 'Two PCs on VLAN 10 and VLAN 20 need to communicate. Which design is correct?',
    choices: [
      'Connect both PCs with a trunk cable',
      'Use a router or L3 switch with interfaces/SVIs in each VLAN',
      'Place both PCs in VLAN 1 only',
      'Enable port security on both access ports',
    ],
    correctIndex: 1,
    explanation: 'End hosts use access ports — inter-VLAN routing happens at a router or multilayer switch SVI.',
    type: 'application',
    concept: 'vlan',
  },
  // CKU-PORT-SECURITY (3)
  {
    id: 'trap-portsec-1',
    ckuId: 'CKU-PORT-SECURITY',
    trapLabel: 'Enabling port security without specifying violation action.',
    objectiveId: '5.6',
    question: 'Port security is enabled with `switchport port-security maximum 2` but no violation mode. What is the default violation action?',
    choices: [
      'protect — drop violator traffic silently',
      'restrict — drop and count violations',
      'shutdown — err-disable the port',
      'No violation action until manually configured',
    ],
    correctIndex: 2,
    explanation: 'Default violation mode is shutdown — the port enters err-disabled when an unknown MAC violates policy.',
    type: 'definition',
    concept: 'port-security',
  },
  {
    id: 'trap-portsec-2',
    ckuId: 'CKU-PORT-SECURITY',
    trapLabel: 'Applying port security to trunk ports.',
    objectiveId: '5.6',
    question: 'Where should port security be applied on a typical access-layer switch?',
    choices: [
      'On trunk ports to the distribution switch',
      'On access ports facing end-user devices',
      'On the SVI interface VLAN 1',
      'Globally on all ports including trunks',
    ],
    correctIndex: 1,
    explanation: 'Port security limits MACs on access ports — trunks carry many MACs and are not typical port-security targets.',
    type: 'application',
    concept: 'port-security',
  },
  {
    id: 'trap-portsec-3',
    ckuId: 'CKU-PORT-SECURITY',
    trapLabel: 'Enabling port security without specifying violation action.',
    objectiveId: '5.6',
    question: 'After a port-security violation shut down Gi0/5, what is the first recovery step?',
    choices: [
      'Reload the switch',
      'Shut/no shut the interface or clear err-disabled via `errdisable recovery`',
      'Delete VLAN 1',
      'Disable STP on Gi0/5',
    ],
    correctIndex: 1,
    explanation: 'Err-disabled ports recover with shut/no shut or errdisable recovery — the violation condition must also be fixed.',
    type: 'troubleshooting',
    concept: 'port-security',
  },
]

function norm(s) {
  return String(s || '').trim().toLowerCase().replace(/\s+/g, ' ')
}

/** Resolve trap label or CKU id to a trap-drill CKU entry. */
export function resolveTrapDrillCku({ trapLabel, ckuId } = {}) {
  if (ckuId) {
    const byId = TRAP_DRILL_CKUS.find(c => c.ckuId === ckuId)
    if (byId) return byId
  }
  if (!trapLabel) return null
  const label = norm(trapLabel)
  const exact = TRAP_DRILL_CKUS.find(c => norm(c.trapLabel) === label)
  if (exact) return exact
  return TRAP_DRILL_CKUS.find(c => {
    const t = norm(c.trapLabel)
    return t.includes(label) || label.includes(t)
  }) || null
}

/** Questions for one trap CKU, or all if no filter. */
export function getTrapDrillQuestions({ trapLabel, ckuId } = {}) {
  const resolved = resolveTrapDrillCku({ trapLabel, ckuId })
  if (resolved) {
    return QUESTIONS.filter(q => q.ckuId === resolved.ckuId)
  }
  if (trapLabel || ckuId) return []
  return [...QUESTIONS]
}

export function getAllTrapDrillQuestions() {
  return [...QUESTIONS]
}
