/** Canonical CCNA IOS command reference — supplements curated packs. */
export const CCNA_COMMAND_REGISTRY = [
  {
    id: 'cmd-show-spanning-tree',
    command: 'show spanning-tree',
    aliases: ['sh spanning-tree', 'sh span'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'switch',
    purpose:
      'Displays Rapid PVST+ topology per VLAN: root bridge ID, root port, designated/blocked ports, and path costs. Compare root election and blocking roles before chasing VLAN or routing issues.',
    example: 'SW1# show spanning-tree',
    syntaxNotes: 'Add vlan <id> or interface <if> for scoped output.',
    objectiveIds: ['2.5'],
    tags: ['switching', 'stp'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-spanning-tree-vlan',
    command: 'show spanning-tree vlan 1',
    aliases: ['sh span vlan 1', 'sh spanning-tree vlan 1'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'switch',
    purpose:
      'Narrows STP output to one VLAN when multiple instances exist under Rapid PVST+. Confirm which port is root, designated, or alternate/blocking for that broadcast domain.',
    example: 'SW1# show spanning-tree vlan 10',
    objectiveIds: ['2.5'],
    tags: ['switching', 'stp', 'vlan'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-spanning-tree-root-primary',
    command: 'spanning-tree vlan 1 root primary',
    aliases: ['spanning-tree vlan 1 priority 24576'],
    mode: 'global config',
    category: 'config',
    device: 'switch',
    purpose:
      'Forces this switch toward root-bridge election by lowering VLAN priority (primary ≈ 24576). Place the root intentionally at distribution/core rather than letting a random access switch win.',
    example: 'SW1(config)# spanning-tree vlan 1 root primary',
    objectiveIds: ['2.5'],
    tags: ['switching', 'stp'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-spanning-tree-portfast',
    command: 'spanning-tree portfast',
    aliases: ['spanning portfast'],
    mode: 'interface config',
    category: 'config',
    device: 'switch',
    purpose:
      'Skips listening/learning on an access port so a host gets connectivity immediately. PortFast belongs only on true edge ports — never on switch-to-switch links.',
    example: 'SW1(config-if)# spanning-tree portfast',
    objectiveIds: ['2.5'],
    tags: ['switching', 'stp', 'portfast'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-spanning-tree-bpduguard',
    command: 'spanning-tree bpduguard enable',
    aliases: ['spanning bpduguard enable'],
    mode: 'interface config',
    category: 'config',
    device: 'switch',
    purpose:
      'Err-disables a PortFast port if it receives a BPDU — protecting against an accidental loop when another switch is plugged into an access port.',
    example: 'SW1(config-if)# spanning-tree bpduguard enable',
    objectiveIds: ['2.5'],
    tags: ['switching', 'stp', 'security'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-cdp-neighbors-detail',
    command: 'show cdp neighbors detail',
    aliases: ['sh cdp nei detail', 'sh cdp neighbors detail'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Shows directly connected Cisco neighbors with Device ID, platform, capabilities, and local/remote port mapping. Use to confirm cabling and L2 adjacencies.',
    example: 'R1# show cdp neighbors detail',
    objectiveIds: ['2.3'],
    tags: ['discovery', 'cdp', 'troubleshooting'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-no-cdp-enable',
    command: 'no cdp enable',
    aliases: ['no cdp enable on interface'],
    mode: 'interface config',
    category: 'config',
    device: 'any',
    purpose:
      'Disables CDP on untrusted edge interfaces so attacker-connected devices cannot learn your topology.',
    example: 'SW1(config-if)# no cdp enable',
    objectiveIds: ['2.3', '5.1'],
    tags: ['discovery', 'cdp', 'security'],
    examWeight: 'reference',
  },
  {
    id: 'cmd-show-access-lists',
    command: 'show access-lists',
    aliases: ['sh access-lists', 'sh ip access-lists'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Lists ACL definitions with sequence numbers, matches, and hit counters. Read top-down order and implicit deny — confirm the first matching permit/deny.',
    example: 'R1# show access-lists',
    objectiveIds: ['5.5'],
    tags: ['security', 'acl'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-access-list-extended',
    command: 'access-list 100 permit tcp any any eq 80',
    aliases: ['ip access-list extended'],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Creates an extended ACL matching source/destination, protocol, and ports — place near the traffic source. First-match-wins with implicit deny at the bottom.',
    example: 'R1(config)# access-list 100 deny ip 192.168.10.0 0.0.0.255 any',
    objectiveIds: ['5.5'],
    tags: ['security', 'acl'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ip-access-group',
    command: 'ip access-group 100 in',
    aliases: ['ip access-group WEB-FILTER out'],
    mode: 'interface config',
    category: 'config',
    device: 'router',
    purpose:
      'Applies a numbered or named ACL to an interface inbound or outbound. Extended ACLs near source; standard ACLs near destination.',
    example: 'R1(config-if)# ip access-group 100 in',
    objectiveIds: ['5.5'],
    tags: ['security', 'acl'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ip-dhcp-pool',
    command: 'ip dhcp pool LAN1',
    aliases: ['ip dhcp pool'],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Defines a DHCP scope on a Cisco router: network, default-router (option 3), and dns-server (option 6). Tie pool network to the correct SVI/subnet.',
    example: 'R1(config)# ip dhcp pool LAN1',
    objectiveIds: ['4.3'],
    tags: ['services', 'dhcp'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ip-dhcp-excluded-address',
    command: 'ip dhcp excluded-address 192.168.10.1 192.168.10.10',
    aliases: ['ip dhcp excluded-address'],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Reserves addresses outside the dynamic lease range — typically gateway, servers, and static devices.',
    example: 'R1(config)# ip dhcp excluded-address 192.168.10.1 192.168.10.10',
    objectiveIds: ['4.3'],
    tags: ['services', 'dhcp'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ip-helper-address',
    command: 'ip helper-address 10.0.0.50',
    aliases: ['ip helper-address'],
    mode: 'interface config',
    category: 'config',
    device: 'router',
    purpose:
      'Relays DHCP broadcasts from a client subnet to a remote DHCP server as unicast — required when server and clients are on different VLANs.',
    example: 'R1(config-if)# ip helper-address 10.0.0.50',
    objectiveIds: ['4.6', '4.3'],
    tags: ['services', 'dhcp', 'routing'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-ip-dhcp-binding',
    command: 'show ip dhcp binding',
    aliases: ['sh ip dhcp binding'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Lists active DHCP leases: client MAC, assigned IP, lease expiration, and type. Confirms clients received correct addresses.',
    example: 'R1# show ip dhcp binding',
    objectiveIds: ['4.3', '4.6'],
    tags: ['services', 'dhcp'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-ip-dhcp-pool',
    command: 'show ip dhcp pool',
    aliases: ['sh ip dhcp pool'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Summarizes each DHCP pool — network, leased vs available addresses, and configured options.',
    example: 'R1# show ip dhcp pool',
    objectiveIds: ['4.3'],
    tags: ['services', 'dhcp'],
    examWeight: 'reference',
  },
  {
    id: 'cmd-aaa-new-model',
    command: 'aaa new-model',
    aliases: [],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Enables the AAA framework so authentication, authorization, and accounting can use TACACS+ or RADIUS instead of line passwords alone.',
    example: 'R1(config)# aaa new-model',
    objectiveIds: ['5.4', '5.7'],
    tags: ['security', 'aaa'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-username-secret',
    command: 'username admin secret Cisco123!',
    aliases: ['username secret'],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Creates a local user account with hashed password (preferred over password). Pair with line vty login local for SSH authentication.',
    example: 'R1(config)# username admin secret Cisco123!',
    objectiveIds: ['5.3', '4.8'],
    tags: ['security', 'management'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-enable-secret',
    command: 'enable secret class',
    aliases: ['enable secret'],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Sets the privileged EXEC (enable) password using MD5 hashing — preferred over enable password.',
    example: 'R1(config)# enable secret class',
    objectiveIds: ['5.3'],
    tags: ['security', 'management'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ntp-server',
    command: 'ntp server 203.0.113.1',
    aliases: ['ntp server'],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Points the device at an NTP time source so syslog timestamps and certificates stay accurate.',
    example: 'R1(config)# ntp server 203.0.113.1',
    objectiveIds: ['4.2'],
    tags: ['services', 'ntp'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-ntp-status',
    command: 'show ntp status',
    aliases: ['sh ntp status', 'sh ntp associations'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Reports clock sync state, stratum, and reference. Verify after ntp server configuration.',
    example: 'R1# show ntp status',
    objectiveIds: ['4.2'],
    tags: ['services', 'ntp'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-snmp-server-community',
    command: 'snmp-server community public RO',
    aliases: ['snmp-server community private RW'],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Enables SNMPv1/v2c read-only (RO) or read-write (RW) access using a community string.',
    example: 'R1(config)# snmp-server community monitor RO',
    objectiveIds: ['4.4'],
    tags: ['services', 'snmp', 'monitoring'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-logging-host',
    command: 'logging host 10.0.0.100',
    aliases: ['logging host'],
    mode: 'global config',
    category: 'config',
    device: 'any',
    purpose:
      'Forwards syslog messages to a remote collector. Combine with logging trap to filter severity (0=emergency through 7=debug).',
    example: 'R1(config)# logging host 10.0.0.100',
    objectiveIds: ['4.5'],
    tags: ['services', 'syslog', 'monitoring'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-logging',
    command: 'show logging',
    aliases: ['sh logging', 'show log'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Displays the local syslog buffer, logging settings, and recent messages.',
    example: 'R1# show logging',
    objectiveIds: ['4.5'],
    tags: ['services', 'syslog', 'monitoring'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-standby-ip',
    command: 'standby 1 ip 192.168.1.1',
    aliases: ['standby ip', 'standby 1 priority 110 preempt'],
    mode: 'interface config',
    category: 'config',
    device: 'router',
    purpose:
      'Configures HSRP group 1 with virtual IP as the shared default gateway. Higher priority wins Active role with preempt.',
    example: 'R1(config-if)# standby 1 ip 192.168.1.1',
    objectiveIds: ['3.5'],
    tags: ['routing', 'fhrp', 'hsrp'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-standby-brief',
    command: 'show standby brief',
    aliases: ['sh standby brief', 'show standby'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Summarizes HSRP groups: Active/Standby state, virtual IP, priority, and interface.',
    example: 'R1# show standby brief',
    objectiveIds: ['3.5'],
    tags: ['routing', 'fhrp', 'hsrp'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-ipv6-unicast-routing',
    command: 'ipv6 unicast-routing',
    aliases: [],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Globally enables IPv6 routing — required before static or OSPFv3 routes will forward.',
    example: 'R1(config)# ipv6 unicast-routing',
    objectiveIds: ['3.3', '1.8'],
    tags: ['routing', 'ipv6'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-ipv6-route',
    command: 'ipv6 route 2001:db8:acad:1::/64 2001:db8:acad:2::1',
    aliases: ['ipv6 route ::/0'],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Installs an IPv6 static route using CIDR prefix notation — default route uses ::/0.',
    example: 'R1(config)# ipv6 route 2001:db8:acad:10::/64 2001:db8:acad:1::1',
    objectiveIds: ['3.3'],
    tags: ['routing', 'ipv6'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-ipv6-route',
    command: 'show ipv6 route',
    aliases: ['sh ipv6 route', 'show ipv6 route static'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Displays the IPv6 routing table with codes C (connected), L (local), S (static), O (OSPF).',
    example: 'R1# show ipv6 route',
    objectiveIds: ['3.3'],
    tags: ['routing', 'ipv6'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-ipv6-interface-brief',
    command: 'show ipv6 interface brief',
    aliases: ['sh ipv6 int brief'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'One-screen view of IPv6 addresses, link-local FE80:: assignments, and interface status per port.',
    example: 'R1# show ipv6 interface brief',
    objectiveIds: ['3.3', '1.8'],
    tags: ['routing', 'ipv6', 'interfaces'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-running-config',
    command: 'show running-config',
    aliases: ['sh run', 'show run'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Displays the active configuration in RAM — what the device runs now, including unsaved changes.',
    example: 'R1# show running-config',
    objectiveIds: ['4.9'],
    tags: ['management', 'ios'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-startup-config',
    command: 'show startup-config',
    aliases: ['sh start', 'show start'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Shows the configuration stored in NVRAM that loads at reboot. Differs from show run if changes were never saved.',
    example: 'R1# show startup-config',
    objectiveIds: ['4.9'],
    tags: ['management', 'ios'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-copy-run-start',
    command: 'copy running-config startup-config',
    aliases: ['copy run start', 'wr', 'write memory'],
    mode: 'privileged EXEC',
    category: 'config',
    device: 'any',
    purpose:
      'Saves the active running config to NVRAM so it survives reload — mandatory last step on every CCNA config task.',
    example: 'R1# copy running-config startup-config',
    objectiveIds: ['4.9'],
    tags: ['management', 'ios'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-interfaces',
    command: 'show interfaces',
    aliases: ['sh interfaces', 'sh int'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Reports line protocol, bandwidth, duplex, errors, and counters per interface. Start here for L1/L2 troubleshooting.',
    example: 'R1# show interfaces gigabitethernet0/0',
    objectiveIds: ['3.6'],
    tags: ['interfaces', 'troubleshooting'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-show-ip-interface-brief',
    command: 'show ip interface brief',
    aliases: ['sh ip int brief'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Compact IP summary: address, OK?, method, and status per interface. Use before show ip route.',
    example: 'R1# show ip interface brief',
    objectiveIds: ['3.6', '4.6'],
    tags: ['interfaces', 'troubleshooting', 'ipv4'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-ping',
    command: 'ping 10.0.0.1',
    aliases: ['ping'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Tests ICMP reachability from the device. Troubleshooting flow: ping gateway, then remote IP, then name (DNS).',
    example: 'R1# ping 10.0.0.1',
    objectiveIds: ['3.6', '1.4'],
    tags: ['troubleshooting', 'connectivity'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-traceroute',
    command: 'traceroute 203.0.113.1',
    aliases: ['traceroute', 'trace'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'any',
    purpose:
      'Maps the hop-by-hop path — identifies where packets stop when ping to a distant host fails.',
    example: 'R1# traceroute 203.0.113.1',
    objectiveIds: ['3.6'],
    tags: ['troubleshooting', 'connectivity'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-switchport-port-security',
    command: 'switchport port-security',
    aliases: ['switchport port-security maximum 1', 'switchport port-security mac-address sticky'],
    mode: 'interface config',
    category: 'config',
    device: 'switch',
    purpose:
      'Enables L2 port security on an access port — limit learned MACs, sticky learning, and violation action.',
    example: 'SW1(config-if)# switchport port-security maximum 1',
    objectiveIds: ['5.6'],
    tags: ['security', 'switching', 'port-security'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-show-port-security',
    command: 'show port-security',
    aliases: ['sh port-security'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'switch',
    purpose:
      'Lists secure MAC addresses, violation counts, and max MACs per port. After violation the port enters err-disabled.',
    example: 'SW1# show port-security',
    objectiveIds: ['5.6'],
    tags: ['security', 'switching', 'port-security'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-default-information-originate',
    command: 'default-information originate',
    aliases: ['default-information originate always'],
    mode: 'router config',
    category: 'config',
    device: 'router',
    purpose:
      'Instructs OSPF to advertise a default route into the domain — typically on the border router with a static default.',
    example: 'R1(config-router)# default-information originate',
    objectiveIds: ['3.4'],
    tags: ['routing', 'ospf'],
    examWeight: 'must-config',
    note: 'Entered under router ospf <process-id> sub-mode.',
  },
  {
    id: 'cmd-passive-interface',
    command: 'passive-interface default',
    aliases: ['passive-interface gigabitethernet0/0', 'no passive-interface'],
    mode: 'router config',
    category: 'config',
    device: 'router',
    purpose:
      'Suppresses OSPF hellos on interfaces that only have hosts — advertises connected networks without forming adjacencies on access ports.',
    example: 'R1(config-router)# passive-interface default',
    objectiveIds: ['3.4'],
    tags: ['routing', 'ospf'],
    examWeight: 'must-config',
    note: 'Entered under router ospf <process-id> sub-mode.',
  },
  {
    id: 'cmd-show-ip-nat-statistics',
    command: 'show ip nat statistics',
    aliases: ['sh ip nat statistics'],
    mode: 'privileged EXEC',
    category: 'verify',
    device: 'router',
    purpose:
      'Summarizes NAT hits, active translations, and inside/outside interface assignments.',
    example: 'R1# show ip nat statistics',
    objectiveIds: ['4.1'],
    tags: ['services', 'nat'],
    examWeight: 'must-verify',
  },
  {
    id: 'cmd-ip-nat-inside-source-static',
    command: 'ip nat inside source static 192.168.1.10 203.0.113.10',
    aliases: ['ip nat inside source static'],
    mode: 'global config',
    category: 'config',
    device: 'router',
    purpose:
      'Creates a permanent one-to-one NAT mapping for inbound server access — inside local to inside global.',
    example: 'R1(config)# ip nat inside source static 192.168.1.10 203.0.113.10',
    objectiveIds: ['4.1'],
    tags: ['services', 'nat'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-configure-terminal',
    command: 'configure terminal',
    aliases: ['conf t', 'config t', 'configure t'],
    mode: 'privileged EXEC',
    category: 'config',
    device: 'any',
    purpose:
      'Enters global configuration mode from privileged EXEC. Required before most config commands — user EXEC (>) cannot configure.',
    example: 'R1# configure terminal',
    objectiveIds: ['1.6'],
    tags: ['management', 'ios'],
    examWeight: 'must-config',
  },
  {
    id: 'cmd-enable',
    command: 'enable',
    aliases: ['en'],
    mode: 'user EXEC',
    category: 'config',
    device: 'any',
    purpose:
      'Enters privileged EXEC mode (#) from user EXEC (>). Required before show commands and configure terminal.',
    example: 'R1> enable',
    objectiveIds: ['1.6'],
    tags: ['management', 'ios'],
    examWeight: 'must-config',
  },
]
