/** CLI config drills for config-heavy objectives + verify drills for interpret objectives.
 *  Each step: { prompt, answer, hint, cliMode, cliPrompt, ... }.
 *  answer may be an array of acceptable strings (case-insensitive, whitespace-normalized).
 */
import { buildCliPrompt, cliModeBlurb, ANSWER_SCOPES } from './cliModeContext.js'

const NAV = ANSWER_SCOPES.mode_nav
const NEXT = ANSWER_SCOPES.next_command

/** Annotate a drill with explicit IOS mode context (99+ contract). */
function d({
  prompt,
  answer,
  hint,
  mode,
  host = 'R1',
  iface = null,
  scope = NEXT,
}) {
  return {
    prompt,
    answer,
    hint,
    cliMode: mode,
    cliHostname: host,
    ...(iface ? { cliInterface: iface } : {}),
    answerScope: scope,
    cliPrompt: buildCliPrompt({ hostname: host, mode, interfaceName: iface }),
    cliModeBlurb: cliModeBlurb({ mode, interfaceName: iface, answerScope: scope }),
  }
}

export const COMMAND_DRILLS = {
  '1.1': [
    d({
      prompt: 'Show a summary of all interfaces with IP addresses and line status',
      answer: ['show ip interface brief'],
      hint: 'Quick L3 interface table — first hop for connectivity checks.',
      mode: 'priv_exec',
      host: 'R1',
    }),
    d({
      prompt: 'Show the MAC address table to see which MAC is learned on which port',
      answer: ['show mac address-table', 'show mac address table'],
      hint: 'Layer 2 forwarding table on a switch.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '1.3': [
    d({
      prompt: 'Show interface status including speed, duplex, VLAN, and err-disabled state',
      answer: ['show interfaces status'],
      hint: 'Physical layer troubleshooting starts here.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
    d({
      prompt: 'Show detailed counters for GigabitEthernet0/1 including CRC errors',
      answer: ['show interfaces gigabitethernet0/1', 'show interfaces gi0/1'],
      hint: 'show interfaces <name> for input errors and CRC.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '1.4': [
    d({
      prompt: 'Show interface error counters (CRC, runts, giants) on all interfaces',
      answer: ['show interfaces counters errors'],
      hint: 'Isolates bad cable vs config issues.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
    d({
      prompt: 'Show any ports in err-disabled state and why',
      answer: ['show interfaces status err-disabled', 'show interfaces status'],
      hint: 'Security violation, BPDU guard, or link-flap protection.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '1.5': [
    d({
      prompt: 'Show dynamically learned MAC addresses and their ports',
      answer: ['show mac address-table dynamic', 'show mac address table dynamic'],
      hint: 'Confirms which port forwards to a given MAC.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
    d({
      prompt: 'Show spanning-tree state for interface Gi0/1 (role and status)',
      answer: ['show spanning-tree interface gi0/1', 'show spanning-tree interface gigabitethernet0/1'],
      hint: 'Blocking port explains one-way traffic.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '1.6': [
    d({
      prompt: 'Enter interface configuration mode for GigabitEthernet0/1',
      answer: ['interface gigabitethernet0/1', 'interface gi0/1', 'int g0/1'],
      hint: "Use 'interface' followed by the interface name.",
      mode: 'global_config',
      host: 'R1',
      scope: NAV,
    }),
    d({
      prompt: 'Assign the IP address 192.168.10.1 with subnet mask 255.255.255.0',
      answer: ['ip address 192.168.10.1 255.255.255.0'],
      hint: 'ip address <address> <mask>',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Enable the interface (bring it up)',
      answer: ['no shutdown', 'no shut'],
      hint: 'Interfaces are shut down by default.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
  ],
  '1.8': [
    d({
      prompt: 'Enable IPv6 routing on the device',
      answer: ['ipv6 unicast-routing'],
      hint: 'Global config command, required to forward IPv6.',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'On interface Gi0/1, configure IPv6 address 2001:db8:acad:1::1/64',
      answer: ['ipv6 address 2001:db8:acad:1::1/64'],
      hint: 'ipv6 address <address>/<prefix-length>',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Enable the interface to use a link-local address automatically generated via EUI-64, in addition to the global address',
      answer: ['ipv6 enable'],
      hint: 'This command alone generates only a link-local address.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
  ],
  '2.1': [
    d({
      prompt: 'Create VLAN 20',
      answer: ['vlan 20'],
      hint: 'Global config command.',
      mode: 'global_config',
      host: 'SW1',
    }),
    d({
      prompt: 'Name VLAN 20 "SALES"',
      answer: ['name sales', 'name SALES'],
      hint: 'Entered while inside VLAN config mode.',
      mode: 'vlan',
      host: 'SW1',
    }),
    d({
      prompt: 'On interface Fa0/5, set it as an access port',
      answer: ['switchport mode access'],
      hint: 'switchport mode <mode>',
      mode: 'interface',
      host: 'SW1',
      iface: 'FastEthernet0/5',
    }),
    d({
      prompt: 'Assign Fa0/5 to VLAN 20',
      answer: ['switchport access vlan 20'],
      hint: 'switchport access vlan <id>',
      mode: 'interface',
      host: 'SW1',
      iface: 'FastEthernet0/5',
    }),
  ],
  '2.2': [
    d({
      prompt: 'Set interface Gi0/1 to trunk mode',
      answer: ['switchport mode trunk'],
      hint: 'switchport mode <mode>',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Set the native VLAN on this trunk to 99',
      answer: ['switchport trunk native vlan 99'],
      hint: 'switchport trunk native vlan <id>',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Restrict the trunk to allow only VLANs 10, 20, and 99',
      answer: ['switchport trunk allowed vlan 10,20,99', 'switchport trunk allowed vlan 10, 20, 99'],
      hint: 'switchport trunk allowed vlan <list> (comma separated, no spaces needed)',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
  ],
  '2.3': [
    d({
      prompt: 'Globally disable CDP on the device',
      answer: ['no cdp run'],
      hint: 'CDP is enabled by default; this is a global config command.',
      mode: 'global_config',
      host: 'SW1',
    }),
    d({
      prompt: 'Re-enable CDP globally',
      answer: ['cdp run'],
      hint: 'Opposite of the previous command.',
      mode: 'global_config',
      host: 'SW1',
    }),
    d({
      prompt: 'On a single interface, disable CDP only on that port',
      answer: ['no cdp enable'],
      hint: 'Interface-level command (note: different keyword than the global one).',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Globally enable LLDP',
      answer: ['lldp run'],
      hint: 'LLDP is disabled by default, unlike CDP.',
      mode: 'global_config',
      host: 'SW1',
    }),
  ],
  '2.7': [
    d({
      prompt: 'Show switch port status for AP uplink (mode, VLAN, speed)',
      answer: ['show interfaces status'],
      hint: 'AP uplink must be correct access/trunk + VLAN before RF tuning.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
    d({
      prompt: 'Show PoE power delivered to connected devices',
      answer: ['show power inline'],
      hint: 'Underpowered AP may boot-loop or drop clients.',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '2.8': [
    d({
      prompt: 'Show WLAN summary — SSID policy, security, and VLAN mapping',
      answer: ['show wlan summary'],
      hint: 'WLC-side SSID config — not just AP radio power.',
      mode: 'priv_exec',
      host: 'WLC1',
    }),
    d({
      prompt: 'Show associated wireless clients and their VLAN/SSID',
      answer: ['show wireless client summary', 'show dot11 associations'],
      hint: 'Association is step one — check VLAN and IP next.',
      mode: 'priv_exec',
      host: 'WLC1',
    }),
  ],
  '2.4': [
    d({
      prompt: 'On interface Gi0/1, add it to EtherChannel group 1 using LACP active mode',
      answer: ['channel-group 1 mode active'],
      hint: 'channel-group <number> mode <active|passive|desirable|auto>',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'On interface Gi0/2, add it to the same EtherChannel group 1 using LACP active mode',
      answer: ['channel-group 1 mode active'],
      hint: 'Same command on the second member interface.',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/2',
    }),
    d({
      prompt: 'Verify the EtherChannel status and member ports',
      answer: ['show etherchannel summary'],
      hint: 'show etherchannel <option>',
      mode: 'priv_exec',
      host: 'SW1',
    }),
  ],
  '3.3': [
    d({
      prompt: 'Configure a static route to network 192.168.30.0/24 via next-hop 10.0.0.2',
      answer: ['ip route 192.168.30.0 255.255.255.0 10.0.0.2'],
      hint: 'ip route <network> <mask> <next-hop>',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'Configure a default static route pointing to next-hop 203.0.113.1',
      answer: ['ip route 0.0.0.0 0.0.0.0 203.0.113.1'],
      hint: 'A default route matches all destinations.',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'Configure a static IPv6 route to 2001:db8:acad:2::/64 via next-hop 2001:db8:acad:1::2',
      answer: ['ipv6 route 2001:db8:acad:2::/64 2001:db8:acad:1::2'],
      hint: 'ipv6 route <prefix>/<length> <next-hop>',
      mode: 'global_config',
      host: 'R1',
    }),
  ],
  '3.4': [
    d({
      prompt: 'Enter OSPF process 1 configuration mode',
      answer: ['router ospf 1'],
      hint: 'Global config command, process ID is locally significant.',
      mode: 'global_config',
      host: 'R1',
      scope: NAV,
    }),
    d({
      prompt: 'Advertise network 10.0.0.0/24 into OSPF area 0 using a wildcard mask',
      answer: ['network 10.0.0.0 0.0.0.255 area 0'],
      hint: 'network <address> <wildcard-mask> area <area-id>',
      mode: 'router',
      host: 'R1',
    }),
    d({
      prompt: 'Set the router ID to 1.1.1.1',
      answer: ['router-id 1.1.1.1'],
      hint: 'Entered inside router ospf config mode.',
      mode: 'router',
      host: 'R1',
    }),
    d({
      prompt: 'Verify OSPF neighbor adjacencies',
      answer: ['show ip ospf neighbor'],
      hint: 'show ip ospf <option>',
      mode: 'priv_exec',
      host: 'R1',
    }),
  ],
  '3.5': [
    d({
      prompt: 'On interface Gi0/1, enable HSRP group 1 with virtual IP 192.168.1.1',
      answer: ['standby 1 ip 192.168.1.1'],
      hint: 'standby <group> ip <virtual-ip>',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Set this router\'s HSRP priority to 150 for group 1',
      answer: ['standby 1 priority 150'],
      hint: 'standby <group> priority <value> (default is 100)',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Enable preemption for HSRP group 1',
      answer: ['standby 1 preempt'],
      hint: 'standby <group> preempt',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
  ],
  '4.1': [
    d({
      prompt: 'Mark interface Gi0/0 as the inside NAT interface',
      answer: ['ip nat inside'],
      hint: 'Applied on the private/LAN-facing interface.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/0',
    }),
    d({
      prompt: 'Mark interface Gi0/1 as the outside NAT interface',
      answer: ['ip nat outside'],
      hint: 'Applied on the public/WAN-facing interface.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Configure PAT overload on Gi0/1 for ACL 1',
      answer: ['ip nat inside source list 1 interface gigabitethernet0/1 overload', 'ip nat inside source list 1 interface gi0/1 overload'],
      hint: 'ip nat inside source list <acl> interface <if> overload',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'Show active NAT translations',
      answer: ['show ip nat translations'],
      hint: 'Verify NAT mappings in privileged EXEC.',
      mode: 'priv_exec',
      host: 'R1',
    }),
  ],
  '4.6': [
    d({
      prompt: 'Create a DHCP pool named LAN_POOL',
      answer: ['ip dhcp pool LAN_POOL', 'ip dhcp pool lan_pool'],
      hint: 'Global config command.',
      mode: 'global_config',
      host: 'R1',
      scope: NAV,
    }),
    d({
      prompt: 'Set the pool network to 192.168.1.0/24',
      answer: ['network 192.168.1.0 255.255.255.0'],
      hint: 'network <network> <mask>, entered inside the DHCP pool.',
      mode: 'dhcp_pool',
      host: 'R1',
    }),
    d({
      prompt: 'Set the default gateway for clients to 192.168.1.1',
      answer: ['default-router 192.168.1.1'],
      hint: 'default-router <ip>',
      mode: 'dhcp_pool',
      host: 'R1',
    }),
    d({
      prompt: 'On the router interface facing remote clients, relay DHCP requests to server 10.0.0.5',
      answer: ['ip helper-address 10.0.0.5'],
      hint: 'Interface-level command.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/0',
    }),
  ],
  '4.8': [
    d({
      prompt: 'Set the domain name to ccna.local (required before generating SSH keys)',
      answer: ['ip domain-name ccna.local'],
      hint: 'Global config command.',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'Generate RSA keys with a modulus of 2048 bits',
      answer: ['crypto key generate rsa modulus 2048', 'crypto key generate rsa'],
      hint: 'crypto key generate rsa modulus <bits>',
      mode: 'global_config',
      host: 'R1',
    }),
    d({
      prompt: 'On the vty lines, allow only SSH for incoming connections',
      answer: ['transport input ssh'],
      hint: 'Entered inside line vty configuration.',
      mode: 'line',
      host: 'R1',
    }),
    d({
      prompt: 'Configure the vty lines to authenticate using the local user database',
      answer: ['login local'],
      hint: 'login local',
      mode: 'line',
      host: 'R1',
    }),
  ],
  '5.3': [
    d({
      prompt: 'Set the enable secret password to "ciscoenable"',
      answer: ['enable secret ciscoenable'],
      hint: 'enable secret <password> (encrypted, preferred over enable password)',
      mode: 'global_config',
      host: 'SW1',
    }),
    d({
      prompt: 'Create a local user "admin" with privilege level 15 and secret "adminpass"',
      answer: ['username admin privilege 15 secret adminpass'],
      hint: 'username <name> privilege <level> secret <password>',
      mode: 'global_config',
      host: 'SW1',
    }),
    d({
      prompt: 'On the console line, require login using the local user database',
      answer: ['login local'],
      hint: 'Entered inside line con 0 configuration.',
      mode: 'line',
      host: 'SW1',
    }),
  ],
  '5.5': [
    d({
      prompt: 'Create a named extended ACL called "BLOCK_TELNET"',
      answer: ['ip access-list extended BLOCK_TELNET', 'ip access-list extended block_telnet'],
      hint: 'ip access-list extended <name>',
      mode: 'global_config',
      host: 'R1',
      scope: NAV,
    }),
    d({
      prompt: 'Add a line denying TCP traffic from any source to any destination on port 23 (Telnet)',
      answer: ['deny tcp any any eq 23', 'deny tcp any any eq telnet'],
      hint: 'deny tcp <source> <destination> eq <port>',
      mode: 'acl_ext',
      host: 'R1',
    }),
    d({
      prompt: 'Add a line permitting all other IP traffic',
      answer: ['permit ip any any'],
      hint: 'There is an implicit deny at the end, so this is needed to allow everything else.',
      mode: 'acl_ext',
      host: 'R1',
    }),
    d({
      prompt: 'Apply this ACL inbound on interface Gi0/0',
      answer: ['ip access-group BLOCK_TELNET in', 'ip access-group block_telnet in'],
      hint: 'ip access-group <name> in|out, entered on the interface.',
      mode: 'interface',
      host: 'R1',
      iface: 'GigabitEthernet0/0',
    }),
  ],
  '5.9': [
    d({
      prompt: 'Show WLAN security settings for WLAN ID 1 (WPA2-PSK / AES)',
      answer: ['show wlan security 1', 'show wlan summary'],
      hint: 'Verify WPA2-AES (CCMP) — not WEP or TKIP.',
      mode: 'priv_exec',
      host: 'WLC1',
    }),
    d({
      prompt: 'Show associated clients and authentication state',
      answer: ['show wireless client summary', 'show dot11 associations'],
      hint: 'PSK mismatch shows associate-but-no-data or repeated deauth.',
      mode: 'priv_exec',
      host: 'WLC1',
    }),
  ],
  '5.6': [
    d({
      prompt: 'On an access port, enable port security',
      answer: ['switchport port-security'],
      hint: 'Interface must already be in access mode.',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Set the maximum number of secure MAC addresses to 2',
      answer: ['switchport port-security maximum 2'],
      hint: 'switchport port-security maximum <number>',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Configure sticky learning of MAC addresses',
      answer: ['switchport port-security mac-address sticky'],
      hint: 'switchport port-security mac-address sticky',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
    d({
      prompt: 'Set the violation action to shutdown the port',
      answer: ['switchport port-security violation shutdown'],
      hint: 'switchport port-security violation <protect|restrict|shutdown> (shutdown is default)',
      mode: 'interface',
      host: 'SW1',
      iface: 'GigabitEthernet0/1',
    }),
  ],
}
