/**
 * OneNote filename → CCNA objective / CKU mapping.
 * Map overrides inline Exam Topic regex when both exist (map wins on conflict).
 */
export const TOPIC_MAP = {
  '01 - Day 1 – Network Devices.md': { objectiveIds: ['1.1'], ckuIds: ['CKU-ROUTER', 'CKU-SWITCH'], mergeGroup: null },
  '02 - Day 2 - Interfaces & Cables.md': { objectiveIds: ['1.3', '1.4'], ckuIds: [], mergeGroup: null },
  '03 - Day 3 - The TCP_IP Model.md': { objectiveIds: ['1.1'], ckuIds: [], mergeGroup: 'tcpip-model', supplemental: true },
  '04 - Day 4 - Intro to the CLI.md': { objectiveIds: ['5.3'], ckuIds: [], mergeGroup: null, supplemental: true },
  '05 - Day 5 - Ethernet LAN Switching pt 1.md': { objectiveIds: ['1.5'], ckuIds: [], mergeGroup: 'ethernet-l2', part: 1 },
  '06 - Day 6 - Ethernet LAN Switching pt 2.md': { objectiveIds: ['1.5'], ckuIds: [], mergeGroup: 'ethernet-l2', part: 2 },
  '07 - Day 7 - IPv4 Addressing pt 1.md': { objectiveIds: ['1.6'], ckuIds: ['CKU-SUBNETTING'], mergeGroup: 'ipv4', part: 1 },
  '08 - Day 8 - IPv4 Addressing pt 2.md': { objectiveIds: ['1.6', '1.7'], ckuIds: [], mergeGroup: 'ipv4', part: 2 },
  '09 - Day 9 - Switch Interfaces.md': { objectiveIds: ['1.3', '1.4'], ckuIds: [], mergeGroup: null },
  '10 - Day 10 - IPv4 Header.md': { objectiveIds: ['1.6'], ckuIds: [], mergeGroup: null, supplemental: true },
  '11 - Day 11 - Routing Fundamentals & Static Routing.md': { objectiveIds: ['3.1', '3.3'], ckuIds: ['CKU-ROUTING-TABLE'], mergeGroup: 'static-route' },
  '12 - Day 12 - The Life of a Packet.md': { objectiveIds: ['3.2'], ckuIds: ['CKU-LONGEST-PREFIX-MATCH'], mergeGroup: null },
  '13 - Day 13 - Subnetting pt 1.md': { objectiveIds: ['1.6'], ckuIds: ['CKU-SUBNETTING'], mergeGroup: 'subnetting', part: 1 },
  '14 - Day 14 - Subnetting pt 2.md': { objectiveIds: ['1.6'], ckuIds: [], mergeGroup: 'subnetting', part: 2 },
  '15 - Day 15 - Subnetting pt 3 - VLSM.md': { objectiveIds: ['1.6'], ckuIds: [], mergeGroup: 'subnetting', part: 3 },
  '16 - Day 16 - VLANs pt 1.md': { objectiveIds: ['2.1'], ckuIds: ['CKU-VLAN'], mergeGroup: 'vlan', part: 1 },
  '17 - Day 17 - VLANs pt 2.md': { objectiveIds: ['2.1', '2.2'], ckuIds: [], mergeGroup: 'vlan', part: 2 },
  '18 - Day 18 - VLANs pt 3.md': { objectiveIds: ['2.1', '2.2'], ckuIds: [], mergeGroup: 'vlan', part: 3 },
  '19 - Day 19 - DTP & VTP.md': { objectiveIds: ['2.2'], ckuIds: [], mergeGroup: null, supplemental: true },
  '20 - Day 20 - Spanning Tree Protocol pt 1.md': { objectiveIds: ['2.5'], ckuIds: ['CKU-STP'], mergeGroup: 'stp', part: 1 },
  '21 - Day 21 - Spanning Tree Protocol pt 2.md': { objectiveIds: ['2.5'], ckuIds: [], mergeGroup: 'stp', part: 2 },
  '22 - Port Fast.md': { objectiveIds: ['2.5'], ckuIds: ['CKU-STP-PORTFAST'], mergeGroup: 'stp-toolkit', supplemental: true },
  '23 - BPDU Guard & BPDU Filter.md': { objectiveIds: ['2.5'], ckuIds: ['CKU-STP-BPDU'], mergeGroup: 'stp-toolkit', supplemental: true },
  '24 - Root Guard.md': { objectiveIds: ['2.5'], ckuIds: [], mergeGroup: 'stp-toolkit', supplemental: true },
  '25 - Loop Guard.md': { objectiveIds: ['2.5'], ckuIds: [], mergeGroup: 'stp-toolkit', supplemental: true },
  '26 - Day 22 - Rapid Spanning Tree Protocol (RSTP).md': { objectiveIds: ['2.5'], ckuIds: ['CKU-RSTP'], mergeGroup: 'stp', part: 3 },
  '27 - Day 23 - EtherChannel.md': { objectiveIds: ['2.4'], ckuIds: ['CKU-ETHERCHANNEL'], mergeGroup: null },
  '28 - Day 24 - Dynamic Routing.md': { objectiveIds: ['3.1', '3.2'], ckuIds: [], mergeGroup: null },
  '29 - Day 25 -  RIP & EIGRP.md': { objectiveIds: ['3.2'], ckuIds: [], mergeGroup: null, supplemental: true },
  '30 - Day 26 - OSPF pt 1.md': { objectiveIds: ['3.4'], ckuIds: ['CKU-OSPF'], mergeGroup: 'ospf', part: 1 },
  '31 - Day 27 - OSPF pt 2.md': { objectiveIds: ['3.4'], ckuIds: ['CKU-OSPF-NEIGHBOR'], mergeGroup: 'ospf', part: 2 },
  '32 - Day 28 - OSPF pt 3.md': { objectiveIds: ['3.4'], ckuIds: ['CKU-OSPF-COST'], mergeGroup: 'ospf', part: 3 },
  '33 - Day 29 - First Hop Redundancy.md': { objectiveIds: ['3.5'], ckuIds: ['CKU-FHRP'], mergeGroup: null },
  '34 - Day 30 - TCP & UDP.md': { objectiveIds: ['1.5'], ckuIds: [], mergeGroup: null, supplemental: true },
  '35 - Day 31 - IPv6 pt 1.md': { objectiveIds: ['1.8'], ckuIds: ['CKU-IPV6'], mergeGroup: 'ipv6', part: 1 },
  '36 - Day 32 - IPv6 pt 2.md': { objectiveIds: ['1.8', '1.9'], ckuIds: [], mergeGroup: 'ipv6', part: 2 },
  '37 - Day 33 - IPv6 pt 3.md': { objectiveIds: ['1.9', '3.3'], ckuIds: [], mergeGroup: 'ipv6', part: 3 },
  '38 - Day 34 - Standard ACLs.md': { objectiveIds: ['5.5'], ckuIds: ['CKU-ACL-STANDARD'], mergeGroup: 'acl', part: 1 },
  '39 - Day 35 - Extended ACLs.md': { objectiveIds: ['5.5'], ckuIds: ['CKU-ACL-EXTENDED'], mergeGroup: 'acl', part: 2 },
  '40 - Day 36 - CDP & LLDP.md': { objectiveIds: ['2.3'], ckuIds: ['CKU-CDP-LLDP'], mergeGroup: null },
  '41 - Day 37 - Network Time Protocol (NTP).md': { objectiveIds: ['4.2'], ckuIds: ['CKU-NTP'], mergeGroup: null },
  '42 - Day 38 - Domain Name System (DNS).md': { objectiveIds: ['4.3'], ckuIds: ['CKU-DNS'], mergeGroup: null },
  '43 - Day 39 - Dynamic Host Configuration Protocol (DHCP).md': { objectiveIds: ['4.3', '4.6'], ckuIds: ['CKU-DHCP'], mergeGroup: null },
  '44 - Day 40 - Simple Network Management Protocol.md': { objectiveIds: ['4.4'], ckuIds: ['CKU-SNMP'], mergeGroup: null },
  '45 - Day 41 - Syslog.md': { objectiveIds: ['4.5'], ckuIds: ['CKU-SYSLOG'], mergeGroup: null },
  '46 - Day 42 - Secure Shell (SSH).md': { objectiveIds: ['4.8'], ckuIds: ['CKU-SSH'], mergeGroup: null },
  '47 - Day 43 - File  Transfer Protocol (FTP) & Trivial File Transfer Protocol (TFTP).md': { objectiveIds: ['4.9'], ckuIds: ['CKU-TFTP-FTP'], mergeGroup: null },
  '48 - Day 44 - Network Address Translation (NAT) pt 1.md': { objectiveIds: ['4.1'], ckuIds: ['CKU-NAT', 'CKU-NAT-TERMS'], mergeGroup: 'nat', part: 1 },
  '49 - Day 45 - Network Address Translation (NAT) pt 2.md': { objectiveIds: ['4.1'], ckuIds: ['CKU-NAT-PAT'], mergeGroup: 'nat', part: 2 },
  '50 - Day 46 - Quality of Service (QoS) pt 1.md': { objectiveIds: ['4.7'], ckuIds: ['CKU-QOS'], mergeGroup: 'qos', part: 1 },
  '51 - Day 47 - Quality of Service (QoS) pt 2.md': { objectiveIds: ['4.7'], ckuIds: [], mergeGroup: 'qos', part: 2 },
  '52 - Day 48 - Security Fundamentals.md': { objectiveIds: ['5.1'], ckuIds: ['CKU-CIA-TRIAD'], mergeGroup: null },
  '53 - Day 49 - Port Security.md': { objectiveIds: ['5.6'], ckuIds: ['CKU-PORT-SECURITY'], mergeGroup: null },
  '54 - Day 50 - DHCP Snooping.md': { objectiveIds: ['5.6'], ckuIds: ['CKU-DHCP-SNOOPING'], mergeGroup: null },
  '55 - Day 51 - Dynamic ARP Inspection (DAI).md': { objectiveIds: ['5.6'], ckuIds: ['CKU-DAI'], mergeGroup: null },
  '56 - Day 52 - LAN Architectures.md': { objectiveIds: ['1.2'], ckuIds: [], mergeGroup: null },
  '57 - Day 53 - WAN Architectures.md': { objectiveIds: ['1.2'], ckuIds: [], mergeGroup: null, supplemental: true },
  '58 - Day 54 - Virtualization & Cloud.md': { objectiveIds: ['1.12'], ckuIds: ['CKU-VIRTUALIZATION'], mergeGroup: null },
  '59 - Containers.md': { objectiveIds: ['1.12'], ckuIds: [], mergeGroup: null, supplemental: true },
  '60 - Virtual Router & Forwarding (VRF).md': { objectiveIds: ['3.1'], ckuIds: [], mergeGroup: null, supplemental: true },
  '61 - Day 55 - Wireless Fundamentals.md': { objectiveIds: ['1.11'], ckuIds: ['CKU-WIRELESS'], mergeGroup: 'wireless', part: 1 },
  '62 - Day 56 - Wireless Architectures.md': { objectiveIds: ['2.6'], ckuIds: [], mergeGroup: 'wireless', part: 2 },
  '63 - Day 57 - Wireless Security.md': { objectiveIds: ['5.8'], ckuIds: [], mergeGroup: 'wireless', part: 3 },
  '64 - Day 58 - Wireless Configuration.md': { objectiveIds: ['2.8'], ckuIds: [], mergeGroup: 'wireless', part: 4 },
  '65 - Day 59 - Intro to Network Automation.md': { objectiveIds: ['6.1'], ckuIds: ['CKU-AUTOMATION'], mergeGroup: null },
  '66 - Day 60 - JSON, XML & YAML.md': { objectiveIds: ['6.3'], ckuIds: ['CKU-JSON-YAML'], mergeGroup: null },
  '67 - Day 61 - REST APIs.md': { objectiveIds: ['6.4'], ckuIds: ['CKU-REST'], mergeGroup: null },
  '68 - REST API Authentication.md': { objectiveIds: ['6.4'], ckuIds: [], mergeGroup: null, supplemental: true },
  '69 - Day 62 - Software-Defined Networking (SDN).md': { objectiveIds: ['6.2'], ckuIds: ['CKU-SDN'], mergeGroup: null },
  '70 - Day 63 - Ansible, Puppet, & Chef.md': { objectiveIds: ['6.5'], ckuIds: ['CKU-ANSIBLE'], mergeGroup: null },
  '71 - Terraform.md': { objectiveIds: ['6.5'], ckuIds: [], mergeGroup: null, supplemental: true },
  '72 - Domain Summaries.md': { objectiveIds: ['1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11', '1.12', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '2.8', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '4.1', '4.2', '4.3', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '4.10', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '5.10', '5.11', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6'], ckuIds: [], mergeGroup: 'domain-summaries', chapter: true },
}

export const ALL_OBJECTIVE_IDS = [
  '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11', '1.12',
  '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '2.8',
  '3.1', '3.2', '3.3', '3.4', '3.5', '3.6',
  '4.1', '4.2', '4.3', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '4.10',
  '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '5.10', '5.11',
  '6.1', '6.2', '6.3', '6.4', '6.5', '6.6',
]

export const OBJECTIVE_GAPS = ['1.10', '3.6', '4.10', '5.2', '5.3', '5.4', '5.7', '5.9', '5.10', '5.11', '6.6']
