#!/usr/bin/env python3
"""Gold batch 25 — OSPF 3.4 q036–q061. Run: python3 scripts/_genGoldBatch25.py"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HAND = {
  "obj-3.4-source-q036": {
    "correct": {"choiceIndex": 2, "explanation": "**`passive-interface default`** silences all, then **`no passive-interface gi0/2`** re-enables hellos on only Gi0/2."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**`active-interface`** is not valid IOS syntax — use **`no passive-interface`** to un-suppress.", "misconceptionTested": "Invented active-interface command"},
      {"choiceIndex": 1, "explanation": "**`active-interface`** does not exist — the negation is **`no passive-interface`**.", "misconceptionTested": "active-interface as passive undo"},
      {"choiceIndex": 3, "explanation": "This suppresses **only Gi0/2** — opposite of the goal (silence everything *except* Gi0/2).", "misconceptionTested": "Single passive-interface for inverse logic"},
    ],
    "examTip": "**Only one intf active:** `passive-interface default` + `no passive-interface <intf>` — common OSPF security pattern.",
  },
  "obj-3.4-source-q037": {
    "correct": {"choiceIndex": 0, "explanation": "After changing RID (via `router-id` or loopback), apply it with **`clear ip ospf process`** in **privileged exec**."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "Shutdown/no shutdown on an interface resets that link but does not force OSPF RID recalculation globally.", "misconceptionTested": "Interface bounce for RID change"},
      {"choiceIndex": 2, "explanation": "**`clear ip ospf`** must be run in **privileged exec** (#), not inside **`config-router`**.", "misconceptionTested": "clear ip ospf in config-router mode"},
      {"choiceIndex": 3, "explanation": "**`clear ospf`** omits **`ip`** — correct syntax is **`clear ip ospf process`**.", "misconceptionTested": "Truncated clear ospf command"},
    ],
    "examTip": "RID change takes effect after **`clear ip ospf process`** (or reload) — not automatic.",
  },
  "obj-3.4-source-q038": {
    "correct": {"choiceIndex": 3, "explanation": "ABRs summarize topology via **Type 3 Summary LSAs** between OSPF areas — they do not flood Type 1/2 across area borders."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Between an **AS** and OSPF is the role of an **ASBR** (Autonomous System Boundary Router), not ABR.", "misconceptionTested": "ABR confused with ASBR"},
      {"choiceIndex": 1, "explanation": "**Type 1 (Router LSA)** stays within a single area — ABRs generate **Type 3** for inter-area.", "misconceptionTested": "Type 1 LSAs cross areas via ABR"},
      {"choiceIndex": 2, "explanation": "**Type 2 (Network LSA)** is generated by the DR on multi-access segments within an area — not exchanged by ABRs.", "misconceptionTested": "Type 2 LSAs exchanged between areas"},
    ],
    "examTip": "ABR = borders between **areas** (Type 3) | ASBR = borders between **routing domains** (Type 5).",
  },
  "obj-3.4-source-q039": {
    "correct": {"choiceIndex": 1, "explanation": "**/14** = first 14 bits fixed → wildcard in octets 3–4 is **0.0.252.255** (bits 15–16 wild in 3rd octet). Two `network` statements assign to **area 0** and **area 1**."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "OSPF `network` uses **wildcard mask**, not CIDR **/22** notation.", "misconceptionTested": "CIDR notation in OSPF network statement"},
      {"choiceIndex": 2, "explanation": "**0.0.254.255** is wrong wildcard for /14, and **255.254.255** is invalid as a second wildcard.", "misconceptionTested": "Miscomputed /14 wildcard mask"},
      {"choiceIndex": 3, "explanation": "Missing **area** keyword and only one statement — OSPF needs separate `network` commands per area.", "misconceptionTested": "Single network statement for multiple areas"},
    ],
    "examTip": "/14 wildcard = **0.0.`252`.255** — 2 host bits in 3rd octet (4−2=252 inverted bits).",
  },
  "obj-3.4-source-q040": {
    "correct": {"choiceIndex": 0, "explanation": "**`show ip ospf database`** displays the **LSDB** — summary of all LSAs (Type 1–5) known to this router."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "**`show ip ospf states`** is not valid IOS — use **`show ip ospf database`**.", "misconceptionTested": "Invented show ip ospf states command"},
      {"choiceIndex": 2, "explanation": "**`show ip ospf neighbors`** lists adjacencies — not the LSA database.", "misconceptionTested": "Neighbor table for LSA summary"},
      {"choiceIndex": 3, "explanation": "**`show ip ospf topology`** is not standard IOS — IS-IS uses `show isis topology`.", "misconceptionTested": "Invented show ip ospf topology command"},
    ],
    "examTip": "LSDB view = **`show ip ospf database`** | Neighbor view = **`show ip ospf neighbor`**.",
  },
  "obj-3.4-source-q041": {
    "correct": {"choiceIndex": 3, "explanation": "Wildcard **0.0.0.63** covers .0–.63. If **GigabitEthernet 0/0** has an IP outside that /26 range, it won't match — hence not in OSPF."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Serial 0/3/0 likely within 197.234.3.0/26 (.0–.63) — it would participate.", "misconceptionTested": "Serial in range excluded from OSPF"},
      {"choiceIndex": 1, "explanation": "Sub-interface .1 typically inherits the parent Serial prefix — if in .0–.63, it participates.", "misconceptionTested": "Sub-interface excluded from wildcard match"},
      {"choiceIndex": 2, "explanation": "Same logic — sub-interface .2 within range would be matched.", "misconceptionTested": "Second sub-interface excluded from match"},
    ],
    "examTip": "Wildcard **0.0.0.63** = /26 (first 64 IPs). IPs ≥ .64 on that interface **won't match** the network statement.",
  },
  "obj-3.4-source-q043": {
    "correct": {"choiceIndex": 0, "explanation": "Multi-area OSPF limits LSA flooding per area → smaller LSDB → **faster SPF convergence** as the direct benefit."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "Hierarchical design **adds** config complexity (ABRs, summaries) — benefit is performance, not simplicity.", "misconceptionTested": "Hierarchical OSPF reduces config work"},
      {"choiceIndex": 2, "explanation": "OSPF hierarchy does not increase **link bandwidth** — it reduces **routing overhead** on those links.", "misconceptionTested": "Hierarchical design increases bandwidth"},
      {"choiceIndex": 3, "explanation": "Security is not the **direct** benefit — reduced SPF scope and faster convergence is.", "misconceptionTested": "Security as primary hierarchical benefit"},
    ],
    "examTip": "OSPF areas → smaller LSDB per area → **faster convergence + less CPU** on SPF recalculation.",
  },
  "obj-3.4-source-q044": {
    "correct": {"choiceIndex": 1, "explanation": "Router B shows **FULL/DR** — it **is** the Designated Router on that broadcast segment."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Router C is **BDR** (Backup DR), not the DR.", "misconceptionTested": "BDR confused with DR"},
      {"choiceIndex": 2, "explanation": "**Router D** is not listed in the neighbor table — cannot be the DR.", "misconceptionTested": "Unlisted router as DR"},
      {"choiceIndex": 3, "explanation": "**Router E** does not appear in the output at all.", "misconceptionTested": "Non-existent router as DR"},
    ],
    "examTip": "In `show ip ospf neighbor` output: **FULL/DR** = that neighbor IS the DR | **FULL/BDR** = backup.",
  },
  "obj-3.4-source-q045": {
    "correct": {"choiceIndex": 1, "explanation": "Router B connects **Area 0 to Area 1** — by definition an **Area Border Router (ABR)**."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**ASBR** redistributes routes from another routing domain — not the same as bordering two OSPF areas.", "misconceptionTested": "ASBR for inter-area OSPF"},
      {"choiceIndex": 2, "explanation": "**DR** is a per-segment role for flooding efficiency — not a router connecting areas.", "misconceptionTested": "DR role confused with ABR"},
      {"choiceIndex": 3, "explanation": "**BDR** backs up the DR on a segment — not related to inter-area connectivity.", "misconceptionTested": "BDR role confused with ABR"},
    ],
    "examTip": "ABR = at least **one interface in area 0 + one in another area** — summarizes with Type 3 LSAs.",
  },
  "obj-3.4-source-q046": {
    "correct": {"choiceIndex": 2, "explanation": "Wildcard **`0.0.0.0`** means **exact host match** for 10.0.0.0 — no interface will match unless its IP is exactly 10.0.0.0. Should be wider wildcard like **`0.0.0.255`**."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Process ID is **locally significant** — 255 is valid and does not affect adjacency.", "misconceptionTested": "Invalid OSPF process ID"},
      {"choiceIndex": 1, "explanation": "Area 255 is valid — OSPF areas are 0–4294967295 (or dotted notation).", "misconceptionTested": "Invalid OSPF area number"},
      {"choiceIndex": 3, "explanation": "**10.0.0.0** is a valid network ID — the issue is the **wildcard mask** being too narrow.", "misconceptionTested": "Invalid network ID in OSPF"},
    ],
    "examTip": "Wildcard **0.0.0.0** = **single host** match — almost never correct for enabling OSPF on a subnet.",
  },
  "obj-3.4-source-q047": {
    "correct": {"choiceIndex": 0, "explanation": "OSPF adjacency requires **matching hello and dead timers** — mismatch prevents neighbor formation."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "Point-to-point links still need matching timers — link type alone does not prevent adjacency.", "misconceptionTested": "P2P link type prevents adjacency"},
      {"choiceIndex": 2, "explanation": "Process IDs are **locally significant** — they do **not** need to match between routers.", "misconceptionTested": "Mismatched process IDs break adjacency"},
      {"choiceIndex": 3, "explanation": "**Area IDs** must match on a shared link, but the stem identifies **timer mismatch** as the cause.", "misconceptionTested": "Area IP mismatch when timers differ"},
    ],
    "examTip": "OSPF adjacency checklist: **area ID + hello/dead timers + subnet + authentication** must match.",
  },
  "obj-3.4-source-q048": {
    "correct": {"choiceIndex": 0, "explanation": "**FULL** state means the router has **complete LSDB synchronization** with its neighbor — all LSAs exchanged and acknowledged."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "**EXSTART** is the state where routers negotiate master/slave for DBD exchange — not yet synced.", "misconceptionTested": "EXSTART as fully synced state"},
      {"choiceIndex": 2, "explanation": "**INIT** means a hello was received but two-way communication not yet confirmed.", "misconceptionTested": "INIT as full synchronization"},
      {"choiceIndex": 3, "explanation": "**EXCHANGE** means DBDs are being traded — LSAs not yet fully requested/downloaded.", "misconceptionTested": "EXCHANGE as fully synced state"},
    ],
    "examTip": "OSPF states: INIT → 2-WAY → EXSTART → EXCHANGE → LOADING → **FULL** (adjacency complete).",
  },
  "obj-3.4-source-q049": {
    "correct": {"choiceIndex": 3, "explanation": "State **FULL/DR** means this router has a **full adjacency** with neighbor 192.168.2.2 (which is the DR)."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**FULL** = adjacency formed successfully — no problem here.", "misconceptionTested": "FULL state indicates problem"},
      {"choiceIndex": 1, "explanation": "Nothing in the output suggests cost recalculation — **FULL** is stable.", "misconceptionTested": "FULL state means recalculating"},
      {"choiceIndex": 2, "explanation": "This router's process is stable — **FULL/DR** confirms successful operation.", "misconceptionTested": "Local recalculation in FULL state"},
    ],
    "examTip": "**FULL** neighbor state = healthy, fully adjacent — no action required.",
  },
  "obj-3.4-source-q050": {
    "correct": {"choiceIndex": 2, "explanation": "**`ip ospf cost 25`** on the less-preferred interface raises its cost — traffic uses the lower-cost link; backup remains via higher cost."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**Priority** affects **DR election**, not path preference or cost.", "misconceptionTested": "OSPF priority for path preference"},
      {"choiceIndex": 1, "explanation": "**`ip ospf route primary`** is not valid IOS syntax.", "misconceptionTested": "Invented ip ospf route primary command"},
      {"choiceIndex": 3, "explanation": "**Passive interface** stops OSPF hellos entirely — removes the link from OSPF, no backup.", "misconceptionTested": "Passive interface for backup path"},
    ],
    "examTip": "Path preference = **cost** (lower wins) | DR election = **priority** — don't confuse the two.",
  },
  "obj-3.4-source-q051": {
    "correct": {"choiceIndex": 3, "explanation": "**FULL/DROTHER** means 192.168.2.2 is neither DR nor BDR — DROTHERs only form **FULL adjacencies with DR and BDR**, not with each other."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "State is **FULL** — adjacency is already formed, not in progress.", "misconceptionTested": "FULL means still forming adjacency"},
      {"choiceIndex": 1, "explanation": "**DROTHER** explicitly means it is **not** the DR.", "misconceptionTested": "DROTHER as designated router"},
      {"choiceIndex": 2, "explanation": "**FULL** state confirms the router IS participating in OSPF.", "misconceptionTested": "DROTHER not participating in area"},
    ],
    "examTip": "DROTHERs form **FULL** with DR/BDR only; DROTHER↔DROTHER stays at **2-WAY**.",
  },
  "obj-3.4-source-q052": {
    "correct": {"choiceIndex": 1, "explanation": "Set OSPF priority **higher than current DR** on the interface: **`ip ospf priority 10`** (> 1) then clear OSPF to force re-election."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**`ospf priority`** under **`config-router`** is wrong mode — priority is set on the **interface**.", "misconceptionTested": "Priority under router OSPF config"},
      {"choiceIndex": 2, "explanation": "Setting an IP address does not affect DR election — **priority** does.", "misconceptionTested": "IP address for DR election"},
      {"choiceIndex": 3, "explanation": "**Cost** affects path selection, not **DR/BDR election** — use **priority** for DR.", "misconceptionTested": "OSPF cost for DR election"},
    ],
    "examTip": "DR election: **highest priority** wins (tie = highest RID) — set on **interface** with `ip ospf priority`.",
  },
  "obj-3.4-source-q053": {
    "correct": {"choiceIndex": 3, "explanation": "**`show ip ospf interface`** displays per-interface OSPF detail including **DR/BDR** addresses and states."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**`show ip ospf neighbor`** shows neighbor states (FULL/DR) but doesn't explicitly list **who is DR on the LAN** as clearly.", "misconceptionTested": "Neighbor table for DR identification"},
      {"choiceIndex": 1, "explanation": "**`show ip ospf database`** shows LSAs — not the direct DR per interface.", "misconceptionTested": "LSDB for per-interface DR display"},
      {"choiceIndex": 2, "explanation": "**`show ip ospf dr`** is not valid IOS syntax.", "misconceptionTested": "Invented show ip ospf dr command"},
    ],
    "examTip": "`show ip ospf interface` → see **DR**, **BDR**, **hello/dead**, **cost**, **network type** per link.",
  },
  "obj-3.4-source-q054": {
    "correct": {"choiceIndex": 3, "explanation": "Router A advertises 10.0.0.0/24 in **area 0**; Router B advertises same subnet in **area 1** — they share a link but **area IDs don't match**, so no adjacency."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Timers default to the same values — the stem shows **area mismatch** as the issue.", "misconceptionTested": "Timer mismatch when areas differ"},
      {"choiceIndex": 1, "explanation": "DR is elected after adjacency forms — adjacency fails first due to area mismatch.", "misconceptionTested": "No DR prevents adjacency"},
      {"choiceIndex": 2, "explanation": "Process IDs are **locally significant** — they never need to match.", "misconceptionTested": "Process ID mismatch breaks OSPF"},
    ],
    "examTip": "Shared link must be in the **same OSPF area** — area mismatch = no hello acceptance → no adjacency.",
  },
  "obj-3.4-source-q055": {
    "correct": {"choiceIndex": 2, "explanation": "Inject a default route into OSPF: **`default-information originate`** under `router ospf` — creates a Type 5 LSA for 0.0.0.0/0."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**`ip route 0.0.0.0 0.0.0.0`** creates the local default — but does not **advertise** it into OSPF for other routers.", "misconceptionTested": "Static default alone propagates into OSPF"},
      {"choiceIndex": 1, "explanation": "**`default-route originate`** is invalid — correct is **`default-information originate`**.", "misconceptionTested": "Misspelled default-information originate"},
      {"choiceIndex": 3, "explanation": "**`network 0.0.0.0 0.0.0.0 area 0`** matches all interfaces — it does not create a default route advertisement.", "misconceptionTested": "Network 0.0.0.0 as default route injection"},
    ],
    "examTip": "OSPF default injection = **`default-information originate [always]`** — requires existing default unless `always` used.",
  },
  "obj-3.4-source-q056": {
    "correct": {"choiceIndex": 0, "explanation": "IOS **`bandwidth`** command uses **kbps** — 2.048 Mbps = **2048** kbps → **`bandwidth 2048`**."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "**2048000000** would be ~2 Tbps in kbps units — far too large.", "misconceptionTested": "Bandwidth in bps instead of kbps"},
      {"choiceIndex": 2, "explanation": "IOS does not accept decimal values for **`bandwidth`** — integer kbps only.", "misconceptionTested": "Decimal Mbps in bandwidth command"},
      {"choiceIndex": 3, "explanation": "**2048000** kbps = ~2 Gbps — off by 1000×.", "misconceptionTested": "Bandwidth in bps divided by 1000"},
    ],
    "examTip": "**`bandwidth`** = kbps always | OSPF cost = reference-BW (default 100 Mbps) ÷ interface BW.",
  },
  "obj-3.4-source-q057": {
    "correct": {"choiceIndex": 3, "explanation": "Priority **0** excludes a router from DR/BDR election: **`ip ospf priority 0`** on the interface."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "**`no ospf designated`** is not valid IOS syntax.", "misconceptionTested": "Invented no ospf designated command"},
      {"choiceIndex": 1, "explanation": "**`no ospf designated`** under `config-router` is also invalid.", "misconceptionTested": "config-router no ospf designated"},
      {"choiceIndex": 2, "explanation": "**Passive interface** removes OSPF from that link entirely — not the same as staying in OSPF but never becoming DR.", "misconceptionTested": "Passive interface to prevent DR role"},
    ],
    "examTip": "**Priority 0** = never DR/BDR | Priority 1 (default) = eligible | Highest priority wins election.",
  },
  "obj-3.4-source-q058": {
    "correct": {"choiceIndex": 1, "explanation": "IOS loopback config: **`interface loopback 0`** then **`ip address 192.168.1.2 255.255.255.0`** — dotted-decimal mask required."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "IOS **`ip address`** does not accept CIDR **/24** notation — use **`255.255.255.0`**.", "misconceptionTested": "CIDR notation in ip address command"},
      {"choiceIndex": 2, "explanation": "**`interface loopback`** without a **number** is incomplete — loopback needs an ID (0, 1, etc.).", "misconceptionTested": "Loopback interface without ID"},
      {"choiceIndex": 3, "explanation": "Missing loopback **number** and would need dotted mask (which it has) — but no ID makes it invalid.", "misconceptionTested": "Unnumbered loopback with dotted mask"},
    ],
    "examTip": "Loopback: **`interface loopback <0-2147483647>`** + **`ip address <ip> <mask>`** — common for OSPF RID.",
  },
  "obj-3.4-source-q059": {
    "correct": {"choiceIndex": 3, "explanation": "MPLS VPN allows **both CE and PE** routers to participate in **area 0** — OSPF sham-link or super-backbone enables this."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "PE routers are not limited to area 0 only — they can connect to any customer area.", "misconceptionTested": "PE restricted to area 0"},
      {"choiceIndex": 1, "explanation": "CE routers can be in any area the customer designs — not forced into area 0.", "misconceptionTested": "CE restricted to area 0"},
      {"choiceIndex": 2, "explanation": "GRE is one option but **not required** — MPLS natively supports OSPF via sham-link.", "misconceptionTested": "GRE mandatory for OSPF over MPLS"},
    ],
    "examTip": "OSPF over MPLS: PE ↔ CE run OSPF in customer's area — MPLS backbone is transparent (sham-link for intra-area).",
  },
  "obj-3.4-source-q060": {
    "correct": {"choiceIndex": 0, "explanation": "Default OSPF interface priority is **1** — all routers are DR-eligible by default."},
    "incorrect": [
      {"choiceIndex": 1, "explanation": "**100** is not the default — OSPF priority defaults to **1** (range 0–255).", "misconceptionTested": "100 as default OSPF priority"},
      {"choiceIndex": 2, "explanation": "**255** is the maximum, not the default.", "misconceptionTested": "Maximum value as default priority"},
      {"choiceIndex": 3, "explanation": "**32768** is the default **STP bridge priority**, not OSPF router priority.", "misconceptionTested": "STP priority confused with OSPF priority"},
    ],
    "examTip": "OSPF priority: **default 1** | **0 = never DR** | **higher wins** DR election (tie → highest RID).",
  },
  "obj-3.4-source-q061": {
    "correct": {"choiceIndex": 3, "explanation": "DR election is **non-preemptive** — new higher priority won't take over until **`clear ip ospf process`** on the **current DR** forces re-election."},
    "incorrect": [
      {"choiceIndex": 0, "explanation": "Interface bounce on your router won't force the **existing DR** to give up its role.", "misconceptionTested": "Local interface bounce forces DR change"},
      {"choiceIndex": 1, "explanation": "**`ospf election force`** is not valid IOS syntax.", "misconceptionTested": "Invented ospf election force command"},
      {"choiceIndex": 2, "explanation": "Clearing OSPF on **your own** router re-joins but existing DR stays — must clear on **current DR**.", "misconceptionTested": "Clear on local router forces DR election"},
    ],
    "examTip": "OSPF DR is **non-preemptive** — incumbent keeps role until it fails or OSPF is cleared on it.",
  },
}

assert len(HAND) == 25, f"Expected 25, got {len(HAND)}"

def fmt_entry(id_, rev):
    body = json.dumps(rev, indent=2)
    indented = "\n".join("  " + line if line else line for line in body.splitlines())
    return f"  '{id_}': {indented},"

lines = [
    "/** Gold reviews — Batch 25: OSPF 3.4 q036–q061 (DR/BDR, ABR, timers, passive). */",
    "export const BATCH25_GOLD = {",
]
for id_, rev in HAND.items():
    lines.append(fmt_entry(id_, rev))
lines.append("}")
lines.append("")

out = ROOT / "src/answerReview/goldAnswerReviewsBatch25.js"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(HAND)} entries to {out.relative_to(ROOT)}")
