#!/usr/bin/env node
/**
 * Compile all clean-question-bank JSON → single runtime module.
 * Excludes question IDs in question-health-registry (needs_fix / quarantined).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DOMAIN_META, DOMAIN_1_OBJECTIVES, EXTRA_CLEAN_OBJECTIVES } from './lib/sourceBankConfig.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const CLEAN_ROOT = join(ROOT, 'data', 'clean-question-bank')
const OUT = join(ROOT, 'src', 'data', 'ccnaCleanQuestions.js')
const REGISTRY = join(ROOT, 'data', 'question-health-registry.json')

function loadExcludedIds() {
  if (!existsSync(REGISTRY)) return new Set()
  const { excludedIds } = JSON.parse(readFileSync(REGISTRY, 'utf-8'))
  return new Set(excludedIds || [])
}

function filterExcluded(questions, excluded) {
  if (!excluded.size) return questions || []
  return (questions || []).filter(q => !q?.id || !excluded.has(q.id))
}

function main() {
  const excluded = loadExcludedIds()
  const bank = {}
  const objectives = []
  let dropped = 0

  const ingest = (objectiveId, path) => {
    if (!existsSync(path)) return
    const { questions } = JSON.parse(readFileSync(path, 'utf-8'))
    const filtered = filterExcluded(questions, excluded)
    dropped += (questions?.length || 0) - filtered.length
    if (filtered.length) {
      bank[objectiveId] = filtered
      objectives.push(objectiveId)
    }
  }

  for (const objectiveId of DOMAIN_1_OBJECTIVES) {
    ingest(objectiveId, join(CLEAN_ROOT, 'domain-1', `${objectiveId}.json`))
  }

  for (const [domainNum, meta] of Object.entries(DOMAIN_META)) {
    const dir = join(CLEAN_ROOT, `domain-${domainNum}`)
    if (!existsSync(dir)) continue
    for (const objectiveId of meta.objectives) {
      ingest(objectiveId, join(dir, `${objectiveId}.json`))
    }
  }

  for (const { objectiveId, domain } of EXTRA_CLEAN_OBJECTIVES) {
    if (objectives.includes(objectiveId)) continue
    ingest(objectiveId, join(CLEAN_ROOT, `domain-${domain}`, `${objectiveId}.json`))
  }

  const out = `// AUTO-GENERATED by scripts/compileCleanQuestionsModule.mjs — do not hand-edit.
// Student-facing clean question bank (domains 1–6). Replaces ccnaQuestionImports.js per objective.
export const CLEAN_BANK_OBJECTIVES = new Set(${JSON.stringify(objectives)})
export const CLEAN_QUESTIONS = ${JSON.stringify(bank, null, 2)}
`
  const meta = `// AUTO-GENERATED by scripts/compileCleanQuestionsModule.mjs — do not hand-edit.
export const CLEAN_BANK_OBJECTIVES = new Set(${JSON.stringify(objectives)})
export const CLEAN_BANK_COUNTS = ${JSON.stringify(Object.fromEntries(objectives.map(id => [id, bank[id].length])))}
`
  writeFileSync(OUT, out)
  writeFileSync(join(ROOT, 'src', 'data', 'ccnaCleanBankMeta.js'), meta)
  const total = Object.values(bank).reduce((n, qs) => n + qs.length, 0)
  const dropMsg = dropped ? ` (${dropped} health-excluded)` : ''
  console.log(`✓ Compiled ${total} clean questions for ${objectives.length} objectives${dropMsg} → ccnaCleanQuestions.js`)
}

main()
