#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const KB = join(__dirname, '..', 'data', 'knowledge-base')
const OUT = join(__dirname, '..', 'src', 'data', 'ccnaKnowledgeBaseDomain4.js')

const FILES = {
  ckus: 'ckus.json',
  glossary: 'glossary.json',
  commandBank: 'command-bank.json',
  examTraps: 'exam-traps.json',
  misconceptions: 'misconceptions.json',
  objectives: 'objectives.json',
  chapters: 'chapters.json',
}

function main() {
  const kb = {}
  for (const [key, file] of Object.entries(FILES)) {
    const path = join(KB, file)
    kb[key] = existsSync(path) ? JSON.parse(readFileSync(path, 'utf-8')) : []
  }
  writeFileSync(OUT, `// AUTO-GENERATED by scripts/compileKnowledgeBaseModule.mjs — do not hand-edit.
export const DOMAIN_4_KB = ${JSON.stringify(kb, null, 2)}
`)
  console.log('✓ Compiled knowledge base → src/data/ccnaKnowledgeBaseDomain4.js')
}

main()
