#!/usr/bin/env node
/** Phase 3 — compile KB readings → app curated patches (GENERATED). */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const COMPILED = join(ROOT, 'data', 'onenote', 'compiled', 'objective-readings.json')
const OUT = join(ROOT, 'src', 'data', 'kbCompiledPatches.js')

function main() {
  if (!existsSync(COMPILED)) {
    console.error('✗ Missing compiled readings. Run: npm run kb:merge-onenote')
    process.exit(1)
  }

  const readings = JSON.parse(readFileSync(COMPILED, 'utf8'))
  const patches = {}
  const objectiveIds = []

  for (const [id, r] of Object.entries(readings)) {
    if (!r.tiers?.beginner?.trim() && !r.bigTakeaway?.trim()) continue
    if (r.confidence !== 'gold' && r.confidence !== 'reviewed') {
      // Still compile draft if tiers are usable — marked in meta
    }
    patches[id] = {
      tiers: r.tiers,
      bigTakeaway: r.bigTakeaway,
      keyPoints: r.keyPoints?.length ? r.keyPoints : undefined,
      source: 'onenote-kb',
      confidence: r.confidence,
      needsReview: r.needsReview,
    }
    objectiveIds.push(id)
  }

  objectiveIds.sort()

  const body = `// GENERATED by scripts/compileKbToCurated.mjs — do not hand-edit.
// Rebuild: npm run kb:compile-curated

/** OneNote-sourced reading patches keyed by objectiveId. */
export const KB_COMPILED_PATCHES = ${JSON.stringify(patches, null, 2)}

export const KB_COMPILED_OBJECTIVE_IDS = new Set(${JSON.stringify(objectiveIds)})
`

  writeFileSync(OUT, body)
  console.log(`✓ Compiled KB patches → src/data/kbCompiledPatches.js (${objectiveIds.length} objectives)`)
}

main()
