#!/usr/bin/env node
/**
 * Compile shelved questions → runtime module for Extra Study mode.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DOMAIN_META } from './lib/sourceBankConfig.mjs'
import { applyAnswerReviewToQuestion } from './lib/generateAnswerReview.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SHELVED_ROOT = join(ROOT, 'data', 'shelved-questions')
const OUT = join(ROOT, 'src', 'data', 'ccnaShelvedQuestions.js')

function loadJson(path) {
  return existsSync(path) ? JSON.parse(readFileSync(path, 'utf-8')) : []
}

function main() {
  const exhibitDependent = []
  const outOfScope = []
  const byObjective = {}
  const byDomain = {}

  for (const [domainNum, meta] of Object.entries(DOMAIN_META)) {
    const dir = join(SHELVED_ROOT, `domain-${domainNum}`)
    const exhibit = loadJson(join(dir, 'exhibit-dependent.json'))
    const oos = loadJson(join(dir, 'out-of-scope.json'))
    byDomain[domainNum] = { name: meta.name, exhibit: exhibit.length, outOfScope: oos.length }

    for (const q of [...exhibit, ...oos]) {
      const base = { ...q, domain: Number(domainNum) }
      const enriched = (base.choices && typeof base.correctIndex === 'number')
        ? applyAnswerReviewToQuestion(base)
        : base
      if (q.reason === 'exhibit-dependent') exhibitDependent.push(enriched)
      else outOfScope.push(enriched)
      ;(byObjective[q.objectiveId] ||= []).push(enriched)
    }
  }

  const approvedPath = join(SHELVED_ROOT, 'approved-promotions.json')
  const approved = loadJson(approvedPath)

  const payload = {
    stats: {
      total: exhibitDependent.length + outOfScope.length,
      exhibitDependent: exhibitDependent.length,
      outOfScope: outOfScope.length,
      byDomain,
    },
    exhibitDependent,
    outOfScope,
    byObjective,
    approvedPromotions: approved,
  }

  writeFileSync(OUT, `// AUTO-GENERATED by scripts/compileShelvedQuestionsModule.mjs — do not hand-edit.
export const SHELVED_BANK = ${JSON.stringify(payload, null, 2)}
`)
  console.log(`✓ Compiled ${payload.stats.total} shelved questions → ccnaShelvedQuestions.js`)
}

main()
