#!/usr/bin/env node
/**
 * Compile all clean-question-bank JSON → single runtime module.
 * Replaces per-domain import files; ccnaQuestionImports.js becomes fallback only.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DOMAIN_META, DOMAIN_1_OBJECTIVES, EXTRA_CLEAN_OBJECTIVES } from './lib/sourceBankConfig.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const CLEAN_ROOT = join(ROOT, 'data', 'clean-question-bank')
const OUT = join(ROOT, 'src', 'data', 'ccnaCleanQuestions.js')

function main() {
  const bank = {}
  const objectives = []

  for (const objectiveId of DOMAIN_1_OBJECTIVES) {
    const path = join(CLEAN_ROOT, 'domain-1', `${objectiveId}.json`)
    if (!existsSync(path)) continue
    const { questions } = JSON.parse(readFileSync(path, 'utf-8'))
    if (questions?.length) {
      bank[objectiveId] = questions
      objectives.push(objectiveId)
    }
  }

  for (const [domainNum, meta] of Object.entries(DOMAIN_META)) {
    const dir = join(CLEAN_ROOT, `domain-${domainNum}`)
    if (!existsSync(dir)) continue
    for (const objectiveId of meta.objectives) {
      const path = join(dir, `${objectiveId}.json`)
      if (!existsSync(path)) continue
      const { questions } = JSON.parse(readFileSync(path, 'utf-8'))
      if (questions?.length) {
        bank[objectiveId] = questions
        objectives.push(objectiveId)
      }
    }
  }

  for (const { objectiveId, domain } of EXTRA_CLEAN_OBJECTIVES) {
    if (objectives.includes(objectiveId)) continue
    const path = join(CLEAN_ROOT, `domain-${domain}`, `${objectiveId}.json`)
    if (!existsSync(path)) continue
    const { questions } = JSON.parse(readFileSync(path, 'utf-8'))
    if (questions?.length) {
      bank[objectiveId] = questions
      objectives.push(objectiveId)
    }
  }

  const out = `// AUTO-GENERATED by scripts/compileCleanQuestionsModule.mjs — do not hand-edit.
// Student-facing clean question bank (domains 1–6). Replaces ccnaQuestionImports.js per objective.
export const CLEAN_BANK_OBJECTIVES = new Set(${JSON.stringify(objectives)})
export const CLEAN_QUESTIONS = ${JSON.stringify(bank, null, 2)}
`
  writeFileSync(OUT, out)
  const total = Object.values(bank).reduce((n, qs) => n + qs.length, 0)
  console.log(`✓ Compiled ${total} clean questions for ${objectives.length} objectives → ccnaCleanQuestions.js`)
}

main()
