#!/usr/bin/env node
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT } from './lib/onenoteUtils.mjs'

const PATCHES = join(ROOT, 'src', 'data', 'kbCompiledPatches.js')
const errors = []

if (!existsSync(PATCHES)) {
  console.error('✗ kbCompiledPatches.js missing — run npm run kb:compile-curated')
  process.exit(1)
}

const text = readFileSync(PATCHES, 'utf8')
if (!text.includes('GENERATED by scripts/compileKbToCurated.mjs')) {
  errors.push('kbCompiledPatches.js is not marked GENERATED — hand edits forbidden')
}
if (!text.includes('KB_COMPILED_PATCHES')) {
  errors.push('kbCompiledPatches.js missing KB_COMPILED_PATCHES export')
}

if (errors.length) {
  console.error('✗ validate:single-source failed:')
  errors.forEach(e => console.error('  -', e))
  process.exit(1)
}

console.log('✓ validate:single-source OK — compiled patches are authoritative')
