export const ROUTING_DRILL_ITEMS = [
  {
    line: 'C    192.168.1.0/24 is directly connected, GigabitEthernet0/0',
    question: 'What is the routing source code for this entry?',
    answer: 'C',
    hint: 'Connected routes use code C.',
    explanation: '**C** marks a directly connected route — the router owns an interface on that subnet, so it needs no routing protocol or static entry to reach it.',
    objectiveId: '3.1',
  },
  {
    line: 'L    192.168.1.1/32 is directly connected, GigabitEthernet0/0',
    question: 'What is the routing source code for this entry?',
    answer: 'L',
    hint: 'Local routes use code L and a /32 mask.',
    explanation: '**L** marks a local route — the router\'s own interface IP as a host route (/32), separate from the C entry for the connected subnet.',
    objectiveId: '3.1',
  },
  {
    line: 'S    10.0.0.0/8 [1/0] via 203.0.113.1',
    question: 'What is the administrative distance for this static route?',
    answer: '1',
    hint: 'Static routes default to AD 1.',
    explanation: 'The first bracketed number **[1/0]** is administrative distance — a manually configured static route defaults to AD 1 (connected routes are AD 0).',
    objectiveId: '3.1',
  },
  {
    line: 'S    10.0.0.0/8 [1/0] via 203.0.113.1',
    question: 'What is the metric for this static route?',
    answer: '0',
    hint: 'The second bracketed number is the metric.',
    explanation: 'The second bracketed number **[1/0]** is the metric — static routes always show a metric of 0 since there\'s no protocol cost calculation.',
    objectiveId: '3.1',
  },
  {
    line: 'O    172.16.0.0/16 [110/20] via 10.1.1.2, 00:05:00, GigabitEthernet0/1',
    question: 'What is the OSPF administrative distance?',
    answer: '110',
    hint: 'OSPF AD is 110.',
    explanation: 'OSPF-learned routes carry Cisco\'s default administrative distance of **110** — higher (less trusted) than static (1) or EIGRP internal (90), lower than RIP (120).',
    objectiveId: '3.1',
  },
  {
    line: 'O    172.16.0.0/16 [110/20] via 10.1.1.2, 00:05:00, GigabitEthernet0/1',
    question: 'What is the outgoing interface?',
    answer: 'GigabitEthernet0/1',
    accept: ['Gi0/1', 'gi0/1', 'GigabitEthernet0/1'],
    hint: 'Last field in the route line.',
    explanation: 'The interface name at the end of the line is the **exit interface** the router forwards matching packets out of.',
    objectiveId: '3.1',
  },
  {
    line: 'D    192.168.20.0/24 [90/130816] via 10.1.1.5, 00:12:44, GigabitEthernet0/2',
    question: 'What is the routing source code for this entry?',
    answer: 'D',
    hint: 'EIGRP-learned routes use code D.',
    explanation: '**D** marks an EIGRP-learned route (historically "Diffusing update algorithm") — its default AD of 90 makes it more trusted than OSPF (110) but less than a static route (1).',
    objectiveId: '3.1',
  },
  {
    line: 'R    203.0.113.0/24 [120/2] via 10.1.1.9, 00:00:22, GigabitEthernet0/3',
    question: 'What is the routing source code for this entry?',
    answer: 'R',
    hint: 'RIP-learned routes use code R.',
    explanation: '**R** marks a RIP-learned route — RIP is the least-trusted common IGP with a default AD of 120.',
    objectiveId: '3.1',
  },
  {
    line: 'S*   0.0.0.0/0 [1/0] via 203.0.113.1',
    question: 'What does the asterisk (*) indicate?',
    answer: 'default route',
    accept: ['default', 'default route', 'candidate default route'],
    hint: '0.0.0.0/0 is the default route.',
    explanation: 'The asterisk flags this entry as a **candidate default route** — 0.0.0.0/0 matches any destination with no more specific route, and shows "Gateway of last resort is 203.0.113.1" at the top of `show ip route`.',
    objectiveId: '3.1',
  },
  {
    line: 'S    10.0.0.0/8 [1/0] via 203.0.113.1\nS    10.0.0.0/8 [5/0] via 203.0.113.5',
    question: 'Which route wins — the [1/0] or the [5/0] entry?',
    answer: '[1/0]',
    accept: ['1/0', 'the [1/0] route', '[1/0]'],
    hint: 'Lower administrative distance wins between routes to the same prefix.',
    explanation: 'When two routes exist for the exact same prefix, the router installs the one with the **lowest administrative distance** — here [1/0] beats [5/0]. The higher-AD entry is a floating static, kept as backup.',
    objectiveId: '3.2',
  },
  {
    line: 'O    172.16.0.0/16 [110/20] via 10.1.1.2\nO    172.16.1.0/24 [110/20] via 10.1.1.6',
    question: 'A packet for 172.16.1.5 arrives. Which route is used?',
    answer: '172.16.1.0/24',
    accept: ['172.16.1.0/24', 'the /24 route', 'the second route'],
    hint: 'Longest prefix match wins regardless of metric or AD.',
    explanation: 'Longest prefix match always wins first, before AD or metric are even considered — **172.16.1.0/24** is more specific than 172.16.0.0/16, so it\'s chosen even though both are OSPF routes with identical AD/metric.',
    objectiveId: '3.2',
  },
  {
    line: 'Gateway of last resort is 203.0.113.1 to network 0.0.0.0',
    question: 'What happens to a packet with no matching route and no default route configured?',
    answer: 'dropped',
    accept: ['dropped', 'drop', 'discarded'],
    hint: 'No match and no default route means the packet cannot be forwarded.',
    explanation: 'With no matching entry and no default route (no gateway of last resort), the router **drops** the packet — it has nowhere to send it.',
    objectiveId: '3.2',
  },
  {
    line: 'S    0.0.0.0/0 [1/0] via 203.0.113.1\nS    0.0.0.0/0 [5/0] via 198.51.100.1',
    question: 'What is the [5/0] default route commonly called?',
    answer: 'floating static route',
    accept: ['floating static', 'floating static route'],
    hint: 'A higher-AD backup route that only activates if the primary goes down.',
    explanation: 'A static route configured with an artificially high AD (here 5, vs. the default 1) is a **floating static route** — a backup path that only gets installed if the primary route disappears from the table.',
    objectiveId: '3.3',
  },
  {
    line: 'ip route 0.0.0.0 0.0.0.0 203.0.113.1',
    question: 'Is this route configured with a next-hop address or an exit interface?',
    answer: 'next-hop',
    accept: ['next-hop', 'next hop', 'next-hop address'],
    hint: 'An IP address at the end means next-hop; an interface name means exit interface.',
    explanation: 'The last field is an IP address (203.0.113.1), so this static route is configured with a **next-hop** address — the router still has to do a recursive lookup to find the exit interface, unlike an exit-interface static route.',
    objectiveId: '3.3',
  },
  {
    line: 'O    10.1.1.0/24 [110/20] via 10.1.1.2, 00:05:00, GigabitEthernet0/1',
    question: 'How many equal-cost paths does this route line show?',
    answer: '1',
    hint: 'Count the "via" entries.',
    explanation: 'There is exactly one **via** clause, so this line shows a single path — OSPF equal-cost multi-path entries would show multiple "via" lines under the same prefix.',
    objectiveId: '3.4',
  },
]

export function generateRoutingProblem() {
  const item = ROUTING_DRILL_ITEMS[Math.floor(Math.random() * ROUTING_DRILL_ITEMS.length)]
  return { ...item }
}
