export const STORAGE_KEYS = {
  progress: 'ccna_progress_v1',
  missed: 'ccna_missed_v1',
  streak: 'ccna_streak_v1',
  quizBank: 'ccna_quiz_bank_v1',
  visualCache: 'ccna_visual_cache_v1',
  events: 'ccna_events_v1',
  cliStats: 'ccna_cli_stats_v1',
  syncCode: 'ccna_sync_code_v1',
  syncLast: 'ccna_sync_last_v1',
  usage: 'ccna_usage_v1',
  tutorChat: 'ccna_tutor_chat_v1',
  mockInterviewChat: 'ccna_mock_interview_chat_v1',
  labDone: 'ccna_lab_done_v1',
  theme: 'ccna_theme_v1',
  onboardDone: 'ccna_onboard_done_v1',
  tourDone: 'ccna_tour_done_v1',
  examDate: 'ccna_exam_date_v1',
  reduceMotion: 'ccna_reduce_motion_v1',
  mockHistory: 'ccna_mock_history_v1',
  examMode: 'ccna_exam_mode_v1',
  nudgeDismissed: 'ccna_nudge_dismissed_v1',
  quizSessionSize: 'ccna_quiz_session_size_v1',
  studyBlock: 'ccna_study_block_v1',
  premiumUnlocked: 'ccna_premium_unlocked_v1',
  tutorTtsEnabled: 'ccna_tutor_tts_v1',
  topicFocusSets: 'ccna_topic_focus_sets_v1',
  topicFocusPins: 'ccna_topic_focus_pins_v1',
  questionHealthFlags: 'ccna_question_health_flags_v1',
  questionHealthSignals: 'ccna_question_health_signals_v1',
  trapDrillPrefill: 'ccna_trap_drill_prefill_v1',
  domainPass: 'ccna_domain_pass_v1',
  domainPassCelebrated: 'ccna_domain_pass_celebrated_v1',
  domainPlacement: 'ccna_domain_placement_v1',
}

/** CustomEvent name for dev/e2e trap-drill prefill handoff. */
export const TRAP_DRILL_PREFILL_EVENT = 'ccna-trap-drill-prefill'
